"use client";

import {useEffect,useState} from "react";

type Patient="gp"|"hq"|null;

export default function HospitalPortal(){
  const [name,setName]=useState("");
  const [patient,setPatient]=useState("");
  const [visit,setVisit]=useState("");
  const [access,setAccess]=useState("");
  const [tried,setTried]=useState(false);
  const [translated,setTranslated]=useState(false);
  const [record,setRecord]=useState<Patient>(null);
  const normalizedName=name.toUpperCase().replace(/[\s.·_-]/g,"");
  const gpName=normalizedName==="GUPAN"||name.trim()==="顾盼";
  const hqName=normalizedName==="HAOQIAN"||normalizedName==="HQIAN"||name.trim()==="郝倩";
  const gp=gpName&&patient.toUpperCase()==="GP-221109"&&visit==="20221109"&&access==="7304";
  const hq=hqName&&patient.toUpperCase()==="HQ-220214"&&visit==="20220214"&&access==="0214";
  const target:Patient=gp?"gp":hq?"hq":null;
  const verify=()=>{setTried(true);setRecord(target)};
  const reset=()=>{setName("");setPatient("");setVisit("");setAccess("");setTried(false);setTranslated(false);setRecord(null)};
  useEffect(()=>{
    if(!record)return;
    try{
      const data=JSON.parse(localStorage.getItem("jia-prototype")||"{}");
      const seen=Array.isArray(data.seen)?data.seen:[];
      const id=record==="hq"?"hq-treatment":"medical";
      if(!seen.includes(id))localStorage.setItem("jia-prototype",JSON.stringify({...data,seen:[...seen,id]}));
      window.dispatchEvent(new Event("jia-progress"));
    }catch{}
  },[record]);
  return <main className="route-page medical-site"><div className="medical-utility"><span>North Harbor Medical Network · NORTH HARBOR / OVERSEAS</span><span>Emergency Care　Harborwell Recovery　Billing　中文</span></div><header><div className="medical-logo"><i>✚</i><span><b>North Harbor</b><small>MEDICAL & RECOVERY NETWORK</small></span></div><nav>Care & Services　 Harborwell Recovery　 Health Library　 <strong>Patient Portal</strong></nav></header><div className="medical-breadcrumb">Home　/　Patients & Visitors　/　MyNorthHarbor Historical Records</div>
    {!record?<div className="portal-entry"><section className="portal-intro"><p className="eyebrow">MYNORTHHARBOR</p><h2>One network,<br/>one secure record.</h2><p>North Harbor Medical Center and Harborwell Behavioral Recovery share this historical-record portal. Use the patient name and identifiers printed on a visit document, laboratory sheet or payment order.</p><div className="medical-network-cards"><span><b>North Harbor Medical Center</b><small>Emergency and outpatient records</small></span><span><b>Harborwell Recovery Center</b><small>Behavioral health and recovery programs</small></span></div><ul><li>Encrypted connection</li><li>Access activity is recorded</li><li>Historical documents only</li></ul></section><section className="portal-login"><div className="secure-badge">🔒 SECURE HISTORICAL RECORD ACCESS</div><h2>Verify your record</h2><p>Enter the patient name and identifiers exactly as they appear on the source document.</p><label>Patient name</label><input placeholder="e.g. JANE DOE" value={name} onChange={e=>{setName(e.target.value);setTried(false)}}/><label>Medical record number</label><input placeholder="e.g. NH-000000" value={patient} onChange={e=>{setPatient(e.target.value);setTried(false)}}/><label>Date of service</label><input placeholder="YYYYMMDD" value={visit} onChange={e=>{setVisit(e.target.value);setTried(false)}}/><label>Document access code</label><input placeholder="4-digit code" value={access} onChange={e=>{setAccess(e.target.value);setTried(false)}}/><button onClick={verify}>Continue to health record</button>{tried&&!target&&<p className="portal-error">We couldn’t match those details. Check the patient name, record number, service date and four-digit document code.</p>}<small>Medical privacy limits this portal to documents explicitly released to the patient or payer.</small></section></div>:
    <div className={`record-app ${record==="hq"?"recovery-record":""}`}><aside><div className="patient-chip"><b>{record==="gp"?"GP":"HQ"}</b><span>{record==="gp"?(translated?"顾盼":"Gu Pan"):(translated?"郝倩":"H. Qian")}<small>{translated?"病历号":"MRN"}: {record==="gp"?"GP-221109":"HQ-220214"}</small></span></div><button className="active">{translated?"概览":"Overview"}</button><button>{translated?"就诊记录":"Visits"}</button><button>{record==="gp"?(translated?"检验结果":"Test Results"):(translated?"项目文件":"Program Documents")} <i>1</i></button><button>{translated?"临床备注":"Clinical Notes"}</button><button>{translated?"账单与转介":"Billing & Referrals"}</button><hr/><button onClick={reset}>{translated?"查询其他记录":"Search another record"}</button></aside><section><div className="record-language"><span>{translated?"当前显示：中文翻译":"Original record in English"}</span><button onClick={()=>setTranslated(value=>!value)}>{translated?"查看英文原文":"中文翻译"}</button></div>{record==="gp"?<GuPanRecord translated={translated}/>:<HaoQianRecord translated={translated}/>}<div className="record-actions"><span>{translated?"健康信息管理处":"Health Information Management"} · (555) 014-2210</span></div></section></div>}
    <footer className="medical-footer">Notice of Privacy Practices　·　Accessibility　·　Language Assistance　·　© 2026 North Harbor Medical Network<br/><small>North Harbor Medical Center and Harborwell Recovery Center are fictional and created for this narrative experience.</small></footer></main>
}

function GuPanRecord({translated}:{translated:boolean}){
  return <><div className="record-top"><div><small>{translated?"已向患者发布 · 2022年11月12日":"RELEASED TO PATIENT · NOV 12, 2022"}</small><h2>{translated?"急诊就诊摘要":"Emergency visit summary"}</h2><p>{translated?"北港（海外）医疗中心 · 急诊科":"North Harbor Medical Center · Emergency Department"}</p></div><button>{translated?"下载 PDF":"Download PDF"}</button></div><div className="record-notice">{translated?"此患者版摘要可能未包含指定医疗记录的全部内容。":"This patient-facing summary may not include every part of the designated medical record."}</div><div className="record-meta"><span><small>{translated?"就诊时间":"Date of service"}</small>{translated?"2022年11月9日 · 03:48":"Nov 09, 2022 · 03:48"}</span><span><small>{translated?"主诊医生":"Attending"}</small>E. Miller, MD</span><span><small>{translated?"就诊类型":"Encounter"}</small>{translated?"急诊 / 门诊":"Emergency / Outpatient"}</span><span><small>{translated?"状态":"Status"}</small>{translated?"已结束":"Closed"}</span></div><article className="clinical-note"><h3>{translated?"就诊原因":"Reason for visit"}</h3><p>{translated?"意识丧失、恶心及记忆缺失。患者表示担忧可能遭遇药物促成的侵犯。":"Loss of consciousness, nausea and memory gap. Patient reports concern for possible drug-facilitated assault."}</p><h3>{translated?"已提供的医疗处置":"Care provided"}</h3><p>{translated?"经患者同意完成法医证据保存。扩展毒理学样本已送往外部实验室，并向患者提供危机援助人员信息。":"Forensic evidence preservation completed with patient consent. Expanded toxicology sent to an outside laboratory. Crisis advocate information offered."}</p><h3>{translated?"就诊后发布的检验结果":"Results released after visit"}</h3><div className="lab-result"><span><b>HSV-2 IgG</b><small>{translated?"样本：血液 · 最终结果":"Specimen: Blood · Final"}</small></span><strong>{translated?"阳性":"POSITIVE"} <small>{translated?"超出参考范围":"Out of range"}</small></strong></div><p className="result-note">{translated?"阳性结果表示既往曾接触该病毒。本项检测无法确定感染来源或确切时间。建议进行后续复诊及抗病毒治疗管理。":"A positive result indicates prior exposure. This test cannot establish the source or exact time of infection. Follow-up and antiviral management were recommended."}</p><h3>{translated?"后续安排":"Follow-up"}</h3><p>{translated?"曾预约行为健康科就诊；患者随后通过自动预约系统取消。":"Behavioral health appointment scheduled; later cancelled by patient through automated scheduling."}</p></article></>
}

function HaoQianRecord({translated}:{translated:boolean}){
  return <><div className="record-top"><div><small>{translated?"已向授权付款人发布 · 2022年3月10日":"RELEASED TO AUTHORIZED PAYER · MAR 10, 2022"}</small><h2>{translated?"港湾康复项目摘要":"Harborwell program summary"}</h2><p>{translated?"港湾行为康复中心 · 稳定干预项目":"Harborwell Behavioral Recovery Center · Stabilization Program"}</p></div><button>{translated?"下载 PDF":"Download PDF"}</button></div><div className="record-notice">{translated?"此付款人版本仅确认服务及转介信息，详细临床记录仍受访问限制。":"This payer-facing document confirms service and referral information only. Detailed clinical notes remain restricted."}</div><div className="record-meta"><span><small>{translated?"入院日期":"Admission"}</small>{translated?"2022年2月14日":"Feb 14, 2022"}</span><span><small>{translated?"出院日期":"Discharge"}</small>{translated?"2022年3月8日":"Mar 08, 2022"}</span><span><small>{translated?"项目":"Program"}</small>{translated?"依赖性行为稳定干预":"Dependency stabilization"}</span><span><small>{translated?"状态":"Status"}</small>{translated?"已完成初始疗程":"Initial course completed"}</span></div><article className="clinical-note"><h3>{translated?"患者及费用责任":"Patient and financial responsibility"}</h3><p>{translated?"患者：郝倩。授权付款人：顾盼。全部费用均已结清，未使用保险报销。":"Patient: H. Qian. Authorized payer: Gu Pan. The balance was paid in full without insurance reimbursement."}</p><h3>{translated?"转介原因":"Reason for referral"}</h3><p>{translated?"就兴奋剂类物质依赖进行评估及监督下的稳定干预，社区应当施行监督责任，严禁兴奋剂类用药。本发布副本未提供临床诊断和用药详情。":"Assessment and supervised stabilization related to stimulant-type substance dependency. The community referral provider is responsible for supervision, and stimulant use is strictly prohibited. The clinical diagnosis and medication details are withheld from this released copy."}</p><h3>{translated?"社区转介":"Community referral"}</h3><div className="referral-card"><span><small>{translated?"转介机构":"REFERRING ORGANIZATION"}</small><b>{translated?"远帆社区互助会":"Yuanfan Community Mutual Aid"}</b><em>{translated?"Yuanfan Community Mutual Aid":"远帆社区互助会"}</em></span><span><small>{translated?"转介编号":"REFERRAL ID"}</small><b>YF-HQ-0214</b></span></div><h3>{translated?"随访状态":"Follow-up status"}</h3><p>{translated?"初始稳定干预已经完成。【当年10月更新】社区随访联系中断，港湾中心未收到经核实的继续治疗记录。":"Initial stabilization was completed. [October update] Community follow-up contact was interrupted, and Harborwell received no verified continuation-of-care record."}</p><h3>{translated?"已发布文件访问记录":"Released-document access log"}</h3><p>{translated?"一个转介联络账户曾于2022年10月19日请求下载本摘要。因文件码多次输入错误，IP后续请求被拒绝。":"A referral-liaison account requested a download of this summary on Oct 19, 2022. After repeated incorrect document-code entries, subsequent requests from the IP address were denied."}</p></article></>
}
