(function(){
'use strict';
const SAVE_KEY='_xiachan_blog_rescue_save_v2';
const OLD_KEY='_xiachan_blog_rescue_save_v1';
const TOTAL_CLUES=24,TOTAL_EGGS=11;
const DATE_ANSWER=['0729','0730','0731','0801','0802','0803','0804'];
const REPLY_ANSWER={m1:'r1',m2:'r3',m3:'r4',m4:'r5',m5:'r2'};
const TIMELINE_INITIAL=['main_stop','diagnose','mock_exam','first_comment','entrance_exam','submit_backup','discharge','small_stop'];
const TIMELINE_ANSWER=['diagnose','main_stop','first_comment','mock_exam','entrance_exam','discharge','small_stop','submit_backup'];
const timelineText={diagnose:['2008.07','知夏确诊病毒性心肌炎'],main_stop:['2008.08.05','大号停更，只留下“对不起”'],first_comment:['2008.08.09','小号第一次给苏晓匿名留言'],mock_exam:['2008.11','苏晓一模失利，小号鼓励她'],entrance_exam:['2009.06.17','苏晓参加中考'],discharge:['2009.06.18','知夏出院'],small_stop:['2009.06.20','小号停更'],submit_backup:['2025.06.12','知夏匿名提交博客备份']};
const clueDefs={
unzip:['备份解压成功','密码940712来自博主生日1994年7月12日。'],dates:['缺失的七天日记','7.29—8.4的日记被恢复，频繁出现头晕、医院和复查。'],mars:['火星文核心句','“不想让晓晓分心，但是我不得不走”说明知夏在主动切断联系。'],last_post:['最后一篇“对不起”','停更不是普通搬家或转学，而是一句无法解释的告别。'],reply_match:['未发送草稿匹配','五条草稿都没有发出，第六条留言没有任何回复。'],draft_letter:['没发给苏晓的长信','知夏隐瞒住院，是怕影响苏晓中考。'],su_blog:['苏晓的寻找日记','苏晓在知夏停更后持续寻找她。'],graduation_logo:['毕业照医院标志','照片角落出现青槐医院标志，否定了“只是搬家”的猜测。'],album_pass:['私密相册口令','“去看海”来自两人中考后的约定。'],hospital_photos:['住院相册','病房窗台、口罩侧脸和吊瓶照片证实知夏生病。'],diary_pass:['私密日记口令','“一起上一中”是两人共同的心愿。'],private_diary:['私密日记完整记录','确诊、住院、隐瞒苏晓和注册小号的过程被恢复。'],small_id:['小号ID','图片备注中藏着小号ID：知了不说夏。'],secret_blog:['隐藏小号博客','知夏住院期间一直匿名关注并鼓励苏晓。'],timeline:['小号时间线闭合','匿名留言、备考、出院和2025投稿记录构成完整证据链。'],final_truth:['博客由知夏本人提交','2025年，知夏匿名提交备份，希望把故事讲完。'],reunion:['留言触发重逢','苏晓通过抢救计划看到博客，两人重新取得联系。'],admin_record:['后台投稿记录','后台显示2025.06.12提交人为林知夏。'],page_six:['隐藏第六页留言','第六页是一封写给偶然到访者的信。'],new_blog:['2025新博客','恢复出知夏当下的设计师生活和养猫日常。'],email_code:['暗号邮箱','输入“夏蝉鸣于夏”收到自动回复：谢谢你，夏天收到啦。'],charity_link:['青槐市儿童公益友链','旧友链连接到潮汐福利院儿童画展。'],sx_backup:['苏晓也提交了备份','后台深层记录显示苏晓也提交了自己的博客备份。'],studio_future:['双人工作室','两人后来成为插画师与设计师，合伙开了工作室。']};
const hints={
unzip:['“破壳日”指一个人的生日。','元数据里写着生日07/12/1994，密码需要六位数字。','输入940712。'],
dates:['缺失标题已经写出了日期范围。','连续选中7月29日、30日、31日和8月1日至4日。','选择7.29—8.4共7天，不选7.28、8.5和8.8。'],
mars:['先识别“晓晓”和“分心”附近的字形。','核心是知夏不想影响晓晓备考。','输入“不想分心”。'],
replies:['先处理指向最明确的“讲义”“照片”“看海”。','一模对应“不要熬夜背历史”；追问去向对应“等我回来再说”。','顺序为：讲义夹在数学书里、不要熬夜背历史、照片我收到了、我也想去看海、等我回来再说。'],
album:['回看7月28日公开日记。','两人约好中考结束后去一个地方。','输入“去看海”。'],
diary:['答案是关于升学的共同心愿，不是旅行。','目标学校是“一中”。','输入“一起上一中”。'],
search:['私密日记提示你：小号ID在毕业照备注中。','点击毕业照下方“调查图片信息”，再搜索得到的ID。','搜索“知了不说夏”。'],
timeline:['先按年份分组：2008、2009、2025。','2008年7月确诊在8月5日停更之前；8月9日才有小号第一条留言。','顺序：确诊→大号停更→小号首条留言→一模→中考→出院→小号停更→提交备份。'],
ending:['这里不是答案判定题，只需要一句真诚的话。','可以写“好久不见”“对不起”“我一直都在”。']};
function defaultState(){return{version:2,unzipped:false,unlockedTabs:['home'],currentTab:'home',selectedDates:[],repairedDates:false,replyPick:{},timelineOrder:[...TIMELINE_INITIAL],timelineSelected:-1,visitor:1307,clues:{},eggs:{},puzzles:{},hintsUsed:{},ending:'',finalMessage:'',musicIndex:0,petalsStarted:false,lastSavedAt:0};}
function mergeState(saved){const b=defaultState(),s=saved&&typeof saved==='object'?saved:{};const out={...b,...s};out.unlockedTabs=Array.isArray(s.unlockedTabs)?[...new Set(['home',...s.unlockedTabs])]:['home'];out.selectedDates=Array.isArray(s.selectedDates)?s.selectedDates.filter(x=>typeof x==='string'):[];out.replyPick=s.replyPick&&typeof s.replyPick==='object'?{...s.replyPick}:{};out.timelineOrder=Array.isArray(s.timelineOrder)&&s.timelineOrder.length===8&&new Set(s.timelineOrder).size===8?[...s.timelineOrder]:[...TIMELINE_INITIAL];out.clues=s.clues&&typeof s.clues==='object'?{...s.clues}:{};out.eggs=s.eggs&&typeof s.eggs==='object'?{...s.eggs}:{};out.puzzles=s.puzzles&&typeof s.puzzles==='object'?{...s.puzzles}:{};out.hintsUsed=s.hintsUsed&&typeof s.hintsUsed==='object'?{...s.hintsUsed}:{};out.currentTab=out.unlockedTabs.includes(s.currentTab)?s.currentTab:'home';out.version=2;return out;}
function norm(v){return String(v||'').trim().toLowerCase().replace(/[\s，,。！？!?.、：:；;《》“”‘’\-_]/g,'');}
const Game={state:defaultState(),
init(){this.load();this.bind();this.renderAll();setInterval(()=>this.save(true),30000);setInterval(()=>this.autoPetals(),9000);},
load(){try{let raw=localStorage.getItem(SAVE_KEY);if(!raw){raw=localStorage.getItem(OLD_KEY);if(raw)localStorage.setItem(SAVE_KEY,raw);}this.state=mergeState(raw?JSON.parse(raw):null);}catch(e){console.warn('读档失败',e);this.state=defaultState();}},
save(silent=false){try{this.state.lastSavedAt=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(this.state));if(!silent)this.toast('进度已保存。','success');return true;}catch(e){console.warn('存档失败',e);if(!silent)this.toast('浏览器无法保存进度，请使用导出存档。','error');return false;}},
manualSave(){const ok=this.save(false);if(ok)this.showDialog('存档管理',`<p>已保存到本浏览器。你也可以导出JSON备份，在其他设备导入。</p><div class="save-tools"><button class="blog-btn" onclick="Game.exportSave()">导出存档</button><button class="blog-btn" onclick="document.getElementById('save-import').click()">导入存档</button><button class="blog-btn" onclick="Game.closeDialog()">继续游戏</button></div>`);},
exportSave(){const blob=new Blob([JSON.stringify(this.state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='夏蝉博客_存档.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);},
importSave(ev){const file=ev.target.files&&ev.target.files[0];ev.target.value='';if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);this.state=mergeState(data);this.save(true);this.renderAll();this.closeDialog();this.toast('存档导入成功。','success');}catch(e){this.toast('存档文件格式不正确。','error');}};reader.readAsText(file,'utf-8');},
bind(){document.addEventListener('mousemove',e=>{const g=document.getElementById('cursor-glow');if(g){g.style.left=e.clientX+'px';g.style.top=e.clientY+'px';}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){this.closeDialog();document.getElementById('clue-panel')?.classList.remove('open');if(typeof Paywall!=='undefined')Paywall.hide();}if(e.key==='Enter'&&e.target?.id==='unzip-password')this.checkUnzip();if(e.key==='Enter'&&e.target?.id==='site-search')this.searchSite();});},
renderAll(){document.getElementById('restore-screen')?.classList.toggle('hidden',this.state.unzipped);document.getElementById('blog-screen')?.classList.toggle('hidden',!this.state.unzipped);if(this.state.unzipped){const p=document.getElementById('boot-progress');if(p)p.style.width='100%';}this.renderTabs();this.renderDates();this.renderReplies();this.renderTimeline();this.renderProgress();this.renderClues();this.renderMission();document.getElementById('recovered-days')?.classList.toggle('hidden',!this.state.repairedDates);document.getElementById('draft-box')?.classList.toggle('hidden',!this.state.puzzles.reply_match);document.getElementById('su-blog')?.classList.toggle('hidden',!this.state.puzzles.su_blog);document.getElementById('private-album')?.classList.toggle('hidden',!this.state.puzzles.album_pass);document.getElementById('private-diary')?.classList.toggle('hidden',!this.state.puzzles.diary_pass);const c=document.getElementById('visitor-counter');if(c)c.textContent=String(this.state.visitor).padStart(6,'0');},
checkUnzip(){const v=norm(document.getElementById('unzip-password')?.value).replace(/\D/g,'');if(v!=='940712'){this.toast('密码不对。先把生日转换成“年份后两位+月+日”的六位数字。','error');this.play('playError');return;}this.state.unzipped=true;this.state.puzzles.unzip=true;this.addClue('unzip',true);this.save(true);this.renderAll();this.toast('解压完成。先修复缺失的七天日记。','success');this.play('playUnlock');if(typeof AudioSys!=='undefined')AudioSys.startAmbience();},
toggleDate(btn){if(this.state.repairedDates)return;const d=btn.dataset.day,set=new Set(this.state.selectedDates);set.has(d)?set.delete(d):set.add(d);this.state.selectedDates=[...set];this.save(true);this.renderDates();this.setFeedback('date-feedback','已选择 '+this.state.selectedDates.length+' 个日期。','');this.play('playClick');},
renderDates(){document.querySelectorAll('#calendar-grid button').forEach(btn=>{const d=btn.dataset.day;btn.classList.toggle('selected',this.state.selectedDates.includes(d));btn.classList.toggle('fixed',this.state.repairedDates&&DATE_ANSWER.includes(d));if(DATE_ANSWER.includes(d))btn.disabled=this.state.repairedDates;});const b=document.getElementById('date-repair');if(b)b.disabled=this.state.repairedDates;},
repairDates(){const p=[...this.state.selectedDates].sort(),a=[...DATE_ANSWER].sort();const missing=a.filter(x=>!p.includes(x)),extra=p.filter(x=>!a.includes(x));if(missing.length||extra.length){let msg='日期区间还不完整。';if(missing.length)msg+='还缺 '+missing.map(this.dayText).join('、')+'。';if(extra.length)msg+='多选了 '+extra.map(this.dayText).join('、')+'。';this.setFeedback('date-feedback',msg,'error');this.play('playError');return;}this.state.repairedDates=true;this.state.puzzles.dates=true;this.addClue('dates');this.addClue('last_post');this.save(true);this.renderAll();this.setFeedback('date-feedback','7天损坏日记已恢复。','success');this.toast('下一步：破译8月4日的火星文。','success');},
dayText(d){return d.startsWith('07')?'7.'+Number(d.slice(2)):'8.'+Number(d.slice(2));},
checkMars(){if(!this.state.repairedDates){this.setFeedback('mars-feedback','先修复缺失日期。','error');return;}const v=norm(document.getElementById('mars-answer')?.value);if(!(/不想.*分心|不要.*分心|不想影响/.test(v))){this.setFeedback('mars-feedback','还不对。答案要概括她不愿影响晓晓备考的想法。','error');this.play('playError');return;}this.state.puzzles.mars=true;this.addClue('mars');this.unlockTab('messages');this.state.currentTab='messages';this.save(true);this.renderAll();this.toast('留言板板块已恢复。','success');this.play('playUnlock');},
pickReply(msg,reply){if(reply)this.state.replyPick[msg]=reply;else delete this.state.replyPick[msg];this.save(true);const row=document.querySelector(`[data-msg="${msg}"]`);row?.classList.remove('correct','wrong');if(row?.querySelector('small'))row.querySelector('small').textContent='';},
renderReplies(){Object.keys(REPLY_ANSWER).forEach(msg=>{const s=document.querySelector(`[data-msg="${msg}"] select`);if(s)s.value=this.state.replyPick[msg]||'';});},
clearReplies(){this.state.replyPick={};this.save(true);document.querySelectorAll('.message-row[data-msg]').forEach(r=>{r.classList.remove('correct','wrong');const s=r.querySelector('select'),sm=r.querySelector('small');if(s)s.value='';if(sm)sm.textContent='';});this.setFeedback('reply-feedback','已清空，可以重新匹配。','');},
checkReplies(){let correct=0,filled=0;Object.entries(REPLY_ANSWER).forEach(([m,a])=>{const row=document.querySelector(`[data-msg="${m}"]`),v=this.state.replyPick[m];row?.classList.remove('correct','wrong');const sm=row?.querySelector('small');if(v)filled++;if(v===a){correct++;row?.classList.add('correct');if(sm)sm.textContent='✓ 语气和内容匹配';}else{row?.classList.add('wrong');if(sm)sm.textContent=v?'这条草稿与留言语境不符':'尚未选择';}});if(correct!==5){this.setFeedback('reply-feedback',`已填${filled}/5，匹配正确${correct}/5。错误项已单独标出。`,'error');this.play('playError');return;}this.state.puzzles.reply_match=true;this.addClue('reply_match');this.addClue('draft_letter');this.save(true);this.renderAll();this.setFeedback('reply-feedback','五条草稿全部匹配，草稿箱已恢复。','success');this.play('playClue');},
unlockAlbum(){this.unlockTab('album');this.state.currentTab='album';this.save(true);this.renderAll();this.toast('相册与私密日记板块已恢复。','success');},
openSuBlog(){if(!this.state.unlockedTabs.includes('messages')){this.toast('先恢复留言板。','error');return;}this.state.puzzles.su_blog=true;this.addClue('su_blog');this.state.currentTab='messages';this.save(true);this.renderAll();document.getElementById('su-blog')?.scrollIntoView({behavior:'smooth'});this.toast('已打开苏晓的博客镜像。','success');},
photoInfo(ev){if(ev?.preventDefault)ev.preventDefault();this.addClue('graduation_logo');this.addClue('small_id');this.showDialog('图片信息','<p>文件名：qxez_2008_graduation.jpg</p><p>拍摄者：陈屿</p><p>右上角建筑标识为<strong>青槐医院</strong>。</p><p>EXIF备注：小号ID为<strong>知了不说夏</strong>。</p><p>现在可以在顶部站内搜索中输入这个ID。</p>');},
checkAlbumPass(){const v=norm(document.getElementById('album-password')?.value);if(v!=='去看海'&&v!=='一起去看海'){this.setFeedback('album-feedback','口令不对。回看7月28日两人的约定。','error');this.play('playError');return;}this.state.puzzles.album_pass=true;this.addClue('album_pass');this.addClue('hospital_photos');this.save(true);this.renderAll();this.setFeedback('album-feedback','私密相册已解锁。','success');this.play('playUnlock');},
checkDiaryPass(){const v=norm(document.getElementById('diary-password')?.value);if(v!=='一起上一中'&&v!=='上一中'){this.setFeedback('diary-feedback','口令不对。答案与两人的升学心愿有关。','error');this.play('playError');return;}this.state.puzzles.diary_pass=true;this.addClue('diary_pass');this.addClue('private_diary');this.save(true);this.renderAll();this.setFeedback('diary-feedback','私密日记已解锁。接下来调查小号ID。','success');this.play('playUnlock');},
searchSite(){if(!this.state.unzipped)return;const raw=document.getElementById('site-search')?.value||'',q=norm(raw);if(!q){this.toast('请输入ID、日期或关键词。','error');return;}const rows=[];if(/知了不说夏|小号|匿名/.test(q))rows.push({title:'小号博客：知了不说夏',desc:'住院期间的匿名留言与2025投稿记录。',act:'secret'});if(/医院|青槐医院|毕业照|照片/.test(q))rows.push({title:'毕业照图片信息',desc:'照片角落出现青槐医院标志，备注里还有小号ID。',act:'photo'});if(/对不起|0805|8月5/.test(q))rows.push({title:'2008.08.05：对不起',desc:'大号最后一篇公开日记。',act:'home'});if(/去看海|海边|约定/.test(q))rows.push({title:'一起去看海',desc:'7月28日公开日记与私密相册口令相关。',act:'home'});if(/一起上一中|一中|心愿/.test(q))rows.push({title:'共同的升学心愿',desc:'私密日记口令相关线索。',act:'album'});if(/林知夏|夏蝉|生日|0712|940712/.test(q))rows.push({title:'博主资料：林知夏',desc:'生日为1994年7月12日。',act:'home'});if(!rows.length){this.showDialog('搜索结果','<p>没有找到完全匹配的内容。</p><p>可尝试：<strong>医院、毕业照、对不起、去看海、一起上一中、知了不说夏</strong>。</p>');return;}this.showDialog(`搜索结果（${rows.length}）`,rows.map((r,i)=>`<button class="friend-link" onclick="Game.openSearchResult('${r.act}')"><b>${i+1}. ${r.title}</b><br><small>${r.desc}</small></button>`).join(''));},
openSearchResult(act){this.closeDialog();if(act==='secret'){if(!this.state.puzzles.diary_pass&&!this.state.clues.small_id){this.toast('先从私密日记或毕业照备注中获得小号ID。','error');return;}this.unlockTab('secret');this.state.currentTab='secret';this.state.puzzles.secret_blog=true;this.addClue('secret_blog');}else if(act==='photo'){if(!this.state.unlockedTabs.includes('messages')){this.toast('先恢复留言板并打开苏晓的博客。','error');return;}this.state.currentTab='messages';this.state.puzzles.su_blog=true;this.photoInfo();}else{if(this.state.unlockedTabs.includes(act))this.state.currentTab=act;}this.save(true);this.renderAll();window.scrollTo({top:0,behavior:'smooth'});},
renderTimeline(){const list=document.getElementById('timeline-list');if(!list)return;list.innerHTML=this.state.timelineOrder.map((id,i)=>{const item=timelineText[id],sel=i===this.state.timelineSelected?' selected':'',pos=id===TIMELINE_ANSWER[i]?' correct-position':'';return `<button class="timeline-item${sel}${pos}" onclick="Game.selectTimeline(${i})"><b>${item[0]}</b><span>${item[1]}</span></button>`;}).join('');},
selectTimeline(i){this.state.timelineSelected=i;this.save(true);this.renderTimeline();},
moveTimeline(delta){const i=this.state.timelineSelected;if(i<0){this.setFeedback('timeline-feedback','先点击一个时间节点。','error');return;}const t=i+delta;if(t<0||t>=8)return;const [x]=this.state.timelineOrder.splice(i,1);this.state.timelineOrder.splice(t,0,x);this.state.timelineSelected=t;this.save(true);this.renderTimeline();this.play('playClick');},
resetTimeline(){this.state.timelineOrder=[...TIMELINE_INITIAL];this.state.timelineSelected=-1;this.save(true);this.renderTimeline();this.setFeedback('timeline-feedback','已恢复初始乱序。','');},
checkTimeline(){let firstWrong=this.state.timelineOrder.findIndex((x,i)=>x!==TIMELINE_ANSWER[i]);if(firstWrong!==-1){const expected=timelineText[TIMELINE_ANSWER[firstWrong]];this.setFeedback('timeline-feedback',`第${firstWrong+1}个位置不对。这里应先出现“${expected[1]}”。`,'error');this.play('playError');return;}this.state.puzzles.timeline=true;this.addClue('timeline');this.addClue('final_truth');this.unlockTab('truth');this.state.currentTab='truth';this.save(true);this.renderAll();this.toast('时间线闭合，最终真相页已恢复。','success');this.play('playUnlock');},
submitEnding(){const msg=(document.getElementById('final-message')?.value||'').trim();if(msg.length<2){this.toast('至少留下一句完整的话。','error');return;}this.state.finalMessage=msg;this.addClue('reunion');const n=this.getClueCount();let type=n>=22?'perfect':n>=16?'true':'normal';this.state.ending=type;this.save(true);this.showEnding(type,msg);},
showEnding(type,msg){const data={normal:['普通结局：被修复的告别','你还原了知夏因病停更的原因，但一些隐藏记录仍未被找到。','有些夏天会结束，有些话会留在草稿箱。'],true:['真相结局：夏天收到回音','你找到了小号博客和投稿记录。苏晓通过抢救计划看到这份博客，两人重新取得联系。','好久不见，是迟到很多年的“我一直都在”。'],perfect:['圆满结局：我们的夏天不会结束','你补齐了两份备份与后来的人生记录。苏晓成为插画师，知夏成为设计师，她们合伙开了工作室。','两份旧备份，在同一个夏天重新并肩。']}[type];const o=document.createElement('div');o.className='ending-overlay';o.innerHTML=`<div class="ending-box"><div class="ending-title">${data[0]}</div><div class="ending-content"><p>${data[1]}</p><p><b>你留下的话：</b>${this.escape(msg)}</p><p style="color:#d780a4">${data[2]}</p><p>线索 ${this.getClueCount()}/${TOTAL_CLUES} · 彩蛋 ${this.getEggCount()}/${TOTAL_EGGS}</p><p class="free-note">所有章节与结局均可免费游玩，自愿支持不会改变结局。</p></div><div class="ending-actions"><button class="blog-btn" onclick="this.closest('.ending-overlay').remove()">继续翻看</button><button class="blog-btn support" onclick="Game.showSupport()">自愿支持作者 ¥1</button></div></div>`;document.body.appendChild(o);this.play(type==='perfect'?'playUnlock':'playClue');},
openAdmin(){this.showDialog('博客后台登录','<p>这是一个几乎与背景融在一起的旧入口。</p><div class="form-line"><input id="admin-pass" class="blog-input" placeholder="后台密码"><button class="blog-btn primary" onclick="Game.checkAdmin()">登录</button></div><p class="free-note">密码可从解压密码继续推理。</p>');},
checkAdmin(){const v=norm(document.getElementById('admin-pass')?.value);if(v!=='940712'&&v!=='xiachan'){this.toast('后台密码不正确。','error');return;}this.addClue('admin_record');let extra='';if(this.state.puzzles.timeline){this.addClue('sx_backup');this.addClue('studio_future');extra='<p>深层记录：苏晓也提交了备份。2025年，两人共同登记了一间设计工作室。</p>';}this.showDialog('后台投稿记录','<p>提交时间：2025.06.12</p><p>提交人：林知夏</p><p>备注：麻烦帮我把故事讲完。</p>'+extra);},
renderMission(){const el=document.getElementById('mission-title'),desc=document.getElementById('mission-desc');if(!el||!desc)return;let m;if(!this.state.repairedDates)m=['恢复缺失的七天日记','在左侧日历选中7.29—8.4的连续日期。','dates'];else if(!this.state.puzzles.mars)m=['破译8月4日的火星文','概括知夏离开前最担心的事情。','mars'];else if(!this.state.puzzles.reply_match)m=['匹配五条未发送草稿','进入留言板，为每条留言选择语境对应的草稿。','replies'];else if(!this.state.puzzles.album_pass)m=['解锁私密相册','答案来自7月28日公开日记里的约定。','album'];else if(!this.state.puzzles.diary_pass)m=['解锁私密日记','答案是两人关于升学的共同心愿。','diary'];else if(!this.state.puzzles.secret_blog)m=['找到隐藏小号博客','调查毕业照信息，再用站内搜索输入小号ID。','search'];else if(!this.state.puzzles.timeline)m=['闭合小号时间线','将8个节点按日期和因果顺序排列。','timeline'];else m=['在真相页留下最后一句话','可以继续探索后台与彩蛋，也可直接完成结局。','ending'];el.textContent=m[0];desc.textContent=m[1];this.currentHint=m[2];},
hintForCurrent(){this.showHint(this.currentHint||'dates');},
openHintPanel(){this.hintForCurrent();},
showHint(id){const arr=hints[id];if(!arr)return;const used=Math.min(this.state.hintsUsed[id]||0,arr.length-1);const levels=arr.map((t,i)=>`<div class="hint-level${i>used?' locked':''}"><strong>${i+1}级${i===0?'方向提示':i===1?'具体提示':'接近答案'}</strong><p>${i<=used?t:'点击“查看下一等级”后显示'}</p></div>`).join('');const buttons=[{text:'关闭',action:()=>this.closeDialog()}];if(used<arr.length-1)buttons.push({text:'查看下一等级',primary:true,action:()=>{this.state.hintsUsed[id]=used+1;this.save(true);this.closeDialog();this.showHint(id);}});this.showDialog('免费分级提示',`<p><b>提示完全免费，不需要付款，也不影响结局。</b></p>${levels}`,buttons);},
renderTabs(){if(!this.state.unlockedTabs.includes(this.state.currentTab))this.state.currentTab='home';document.querySelectorAll('.tab').forEach(t=>{const id=t.dataset.tab;t.classList.toggle('locked',!this.state.unlockedTabs.includes(id));t.classList.toggle('active',this.state.currentTab===id);t.setAttribute('aria-current',this.state.currentTab===id?'page':'false');});document.querySelectorAll('.tab-page').forEach(p=>p.classList.toggle('active',p.dataset.page===this.state.currentTab));},
goTab(tab){if(!this.state.unlockedTabs.includes(tab)){this.toast('这个板块还没修复。请先完成当前目标。','error');return;}this.state.currentTab=tab;this.save(true);this.renderTabs();this.play('playClick');window.scrollTo({top:document.querySelector('.tabs')?.offsetTop||0,behavior:'smooth'});},
unlockTab(tab){if(!this.state.unlockedTabs.includes(tab))this.state.unlockedTabs.push(tab);},
addClue(id,silent=false){const d=clueDefs[id];if(!d||this.state.clues[id])return;this.state.clues[id]={title:d[0],desc:d[1],at:Date.now()};this.save(true);this.renderProgress();this.renderClues();if(!silent){this.toast('新线索：'+d[0],'success');this.play('playClue');}},
foundEgg(id,name){if(this.state.eggs[id])return;this.state.eggs[id]={name,at:Date.now()};this.save(true);this.toast('发现彩蛋：'+name,'success');this.play('playClue');},
getClueCount(){return Object.keys(this.state.clues).length},getEggCount(){return Object.keys(this.state.eggs).length},
renderProgress(){const n=this.getClueCount(),pct=Math.min(100,Math.round(n/TOTAL_CLUES*100));const m=document.getElementById('repair-meter'),p=document.getElementById('repair-percent'),c=document.getElementById('clue-count');if(m)m.style.width=pct+'%';if(p)p.textContent=pct+'%';if(c)c.textContent=n+'/'+TOTAL_CLUES;},
renderClues(){const list=document.getElementById('clue-list');if(!list)return;const entries=Object.entries(this.state.clues).sort((a,b)=>a[1].at-b[1].at);list.innerHTML=entries.length?entries.map(([id,c])=>`<div class="clue-item" data-clue="${id}"><div class="clue-title">${this.escape(c.title)}</div><div class="clue-desc">${this.escape(c.desc)}</div></div>`).join(''):'<div class="clue-item"><div class="clue-title">暂无线索</div><div class="clue-desc">完成当前修复目标后，线索会自动记录在这里。</div></div>';},
toggleClues(){document.getElementById('clue-panel')?.classList.toggle('open');},
showSupport(){if(typeof Paywall==='undefined'){this.toast('支持组件未加载，但不影响游戏。','error');return;}Paywall.show({qrCode:'paycode.png',price:'¥1',title:'自愿支持《夏蝉博客》',studio:'abc工作室'});},
confirmReset(){this.showDialog('重新开始','<p>重新开始会清除当前游戏进度，但不会清除自愿支持记录。</p><label class="field-label" for="reset-confirm">请输入“重新修复”确认</label><input id="reset-confirm" class="blog-input" placeholder="重新修复">',[{text:'取消',action:()=>this.closeDialog()},{text:'确认清除',primary:true,action:()=>{if(norm(document.getElementById('reset-confirm')?.value)!=='重新修复'){this.toast('请输入“重新修复”。','error');return;}localStorage.removeItem(SAVE_KEY);localStorage.removeItem(OLD_KEY);location.reload();}}]);},
showDialog(title,content,buttons){this.closeDialog();const root=document.getElementById('dialog-root'),o=document.createElement('div');o.className='dialog-overlay';o.innerHTML=`<div class="dialog-box" role="dialog" aria-modal="true" aria-label="${this.escape(title)}"><div class="dialog-title">${title}</div><div class="dialog-content">${content}</div><div class="dialog-actions"></div></div>`;const a=o.querySelector('.dialog-actions');(buttons?.length?buttons:[{text:'关闭',action:()=>this.closeDialog()}]).forEach(x=>{const b=document.createElement('button');b.className='blog-btn'+(x.primary?' primary':'');b.textContent=x.text;b.addEventListener('click',x.action);a.appendChild(b)});o.addEventListener('click',e=>{if(e.target===o)this.closeDialog();});root.appendChild(o);setTimeout(()=>o.querySelector('input,button')?.focus(),0);this.play('playClick');},
closeDialog(){document.querySelector('.dialog-overlay')?.remove();},
setFeedback(id,text,type=''){const el=document.getElementById(id);if(!el)return;el.textContent=text;el.className='inline-feedback'+(type?' '+type:'');},
toast(text,type=''){const root=document.getElementById('toast-root')||document.body,t=document.createElement('div');t.className='toast '+type;t.textContent=text;root.appendChild(t);requestAnimationFrame(()=>t.classList.add('show'));setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),250)},2600);},
escape(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));},
play(name){try{if(typeof AudioSys!=='undefined'&&AudioSys[name])AudioSys[name]();}catch(e){}},
showDoodle(){this.foundEgg('doodle','边角涂鸦');this.showDialog('边角涂鸦','<figure class="photo-card"><img src="doodle-friends.svg" alt="知夏和苏晓一起看海的涂鸦"><figcaption>蓝色圆珠笔写着：一起去看海。</figcaption></figure>');},
hiddenPageSix(){this.addClue('page_six');this.foundEgg('page_six','留言板第6页');this.showDialog('留言板第6页','<p>如果你偶然来到这里，请替我告诉晓晓：不是她做错了什么。</p>');},
showMaterialSite(){this.foundEgg('material','仍亮着的友链');this.showDialog('动漫素材站','<p>页面还能访问，但大多数图片已经失链。角落挂着“欢迎交换友链”的按钮。</p>');},
deadForum(){this.foundEgg('dead_forum','失效友链提示');this.showDialog('漫展论坛','<p>该页面已失效。</p><p style="color:#d780a4">有些网站会消失，但有些记忆不会。</p>');},
qinghuaiCharity(){this.addClue('charity_link');this.foundEgg('charity_link','系列世界观联动友链');this.showDialog('青槐市儿童公益','<p>恢复到一条“潮汐福利院儿童画展”的旧横幅。</p>');},
olympicEgg(){this.foundEgg('olympic','2008年8月8日');this.showDialog('2008.08.08','<p>开幕式那天，病房走廊的电视很吵。知夏在草稿里写：晓晓一定也在看吧。</p>');},
bumpCounter(){this.state.visitor++;if(this.state.visitor===1314)this.foundEgg('1314','访客计数1314');this.save(true);this.renderAll();this.play('playClick');},
playBlogMusic(){const tracks=['卡农 Piano ver.','夏影 MIDI','鸟之诗 八音盒'];this.state.musicIndex=(this.state.musicIndex+1)%tracks.length;const el=document.getElementById('player-screen');if(el)el.textContent='♪ '+tracks[this.state.musicIndex];this.save(true);this.play('playChime');},
openNewBlog(){this.addClue('new_blog');this.foundEgg('new_blog','2025新博客');this.showDialog('2025新博客镜像','<p>林知夏，设计师。最近更新：收养了一只橘猫，给工作室换了蓝色窗帘。</p>');},
autoPetals(){if(!this.state.unzipped||document.hidden||matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(let i=0;i<3;i++){const p=document.createElement('i');p.className='petal';p.style.left=Math.random()*100+'vw';p.style.animationDuration=6+Math.random()*5+'s';document.getElementById('petal-layer')?.appendChild(p);setTimeout(()=>p.remove(),12000);}}
};
window.Game=Game;window.addEventListener('DOMContentLoaded',()=>Game.init());
})();
