(()=>{
'use strict';
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const TEST_MODE=window.__TEST_MODE__===true;
const el={start:$('#startScreen'),game:$('#game'),newBtn:$('#newGameBtn'),contBtn:$('#continueGameBtn'),view:$('#view'),title:$('#viewTitle'),sub:$('#viewSubtitle'),clock:$('#clock'),night:$('#nightLabel'),account:$('#accountBadge'),state:$('#systemState'),log:$('#log'),memo:$('#memo'),overlay:$('#overlay'),overlayCard:$('#overlayCard'),videoOverlay:$('#videoOverlay'),video:$('#accidentVideo'),videoLabel:$('#videoLabel'),skipVideo:$('#skipVideoBtn'),reportOverlay:$('#reportOverlay'),reportText:$('#reportText'),toast:$('#toast'),hintBtn:$('#hintBtn'),hintBadge:$('#hintBadge'),parser:$('#parserState')};
const SAVE_KEY='accident-report-night-v1';
const initialState=()=>({chapter:0,step:0,night:1,time:'22:06',view:'desk',account:'夜班行政',audit:false,permissions:{schedule:true,equipment:true,property:true,reports:true,evidence:false},seen:{},evidence:[],answered:{},attempts:{},hints:{},history:[],logs:[],flags:{},ending:null,startedAt:Date.now()});
let S=initialState(), overlayResolver=null, videoResolver=null, audioCtx=null, videoAudio=null, videoSfxTimer=null;

const TASKS={
 q1:{title:'这份事故报告最不正常的地方是什么？',prompt:'回放里的事故发生在今天 10:17；报告元数据里还记录了另一个时间。请用自己的话说明两者为什么不正常。',core:[['昨晚','提前','事先','发生前','前一晚','事故前','早于','早一天','比事故早','还没发生','尚未发生'],['创建','生成','写好','报告','出现','已经有了']],need:2,hints:['不要先分析事故原因，先看“报告是什么时候出现的”。','对比事故发生时间 10:17 与报告创建时间 23:11。','报告在事故发生前一晚就已经创建——它记录的是尚未发生的事故。'],partial:'方向接近。再明确一点：异常的是“事故”本身，还是“报告出现的时间”？'},
 q2:{title:'事故为什么从茶水间转移到了消防楼梯？',prompt:'不要只解释“怎么摔倒”，试着解释为什么今天会有更多人经过消防楼梯。',core:[['昨天','之前','整改','停用','饮水机','饮水设备','停了','关了','处理'],['路线','绕路','去四楼','改走','人流','楼梯']],need:2,hints:['不要只看事故发生的一瞬间。想想昨天有什么事情改变了员工原本的行动。','回看昨天填写的整改措施，以及今天员工为什么必须去其他楼层接水。','停用三楼饮水设备后，员工改走消防楼梯去其他楼层接水，昨天的整改制造了新的次生风险。'],partial:'你已经抓到直接诱因了，但还缺“为什么今天这里的人突然变多”。'},
 q3:{title:'两年归档的抽样记录里，真正稳定的是什么？',prompt:'当前页面展示的是两年事故归档中的 6 条抽样。地点、类型、人员都在变化，请指出异常稳定的指标。',core:[['损失','金额','成本','赔付','经济','钱','赔偿'],['稳定','接近','差不多','固定','区间']],need:2,hints:['先别看事故类型，观察每条记录最右侧的数值。','比较不同月份的“预计损失/实际损失”。','事故千差万别，但每月被系统收敛后的损失金额总落在相近区间。'],partial:'你已经注意到数字了，再说清楚“哪个数字”和“它有什么共同点”。'},
 q4:{title:'为什么系统更容易把事故落到这些员工身上？',prompt:'结合人员价值模型与历史事故，解释系统的选择逻辑。',core:[['便宜','低成本','损失更小','经济损失','最低损失','成本','赔偿更少','赔得少','赔得更少','钱更少'],['人','员工','人员','价值','价格','赔付','选谁','谁受伤']],need:2,hints:['把“事故受害者”与“人员价值模型”放在一起看。','系统并没有给所有人的受伤赋予相同代价。','系统在比较损失成本：某些员工受轻伤的短期成本，比高价值设备停机或核心员工受伤更低。'],partial:'你已经接近了。关键不是谁更“倒霉”，而是谁在模型里更“便宜”。'},
 q5:{title:'为什么让李闻请假仍然不能解决问题？',prompt:'李闻不在公司后，事故候选人换成了林姐。用你的话解释发生了什么。',core:[['风险','事故','危险','问题还在','没有解决','没解决'],['转移','换人','换了个人','换一个','另一个','重新计算','重算','下一个','替代']],need:2,hints:['你改变了“谁在现场”，但没有改变系统的优化目标。','观察候选人名单：系统在李闻不可用后做了什么？','风险没有消失，系统只是重新计算并把事故转移给下一个更低成本的对象。'],partial:'对，李闻安全了。但系统为什么马上出现了另一个名字？'},
 q6:{title:'你准备怎样制造一次“无人受伤”的事故？',prompt:'请描述一个完整方案：人员如何离开事故区域、由什么设备承担损失，以及怎样在受控测试中形成真实财产损失。核心方向正确即可。',core:[['无人','没人','清空','封闭','空区','不让人','撤走','人员撤离','清场'],['设备','机架','机器','财产','测试设备'],['测试','受控','故障','损坏','报废','触发']],need:3,bonusNeed:3,hints:['目标不是“假装发生事故”，而是让系统认可一笔真实损失，同时不让任何人在附近。','线下设备清单里有一台仍按高账面价值登记的淘汰测试机架。','清空测试区人员，在受控测试中让高账面价值的旧设备发生故障/损坏，让系统用财产损失而不是人员伤害完成风险收敛。'],partial:'方向接近，但安全闭环还不完整：人员清场、设备对象、受控损坏这三部分都要交代。'},
 q7:{title:'为什么衡损系统仍然需要夜班行政点击“提交”？',prompt:'结合纸质授权单、老杨的旧工单和程越打印的邮件，解释为什么衡损仍然需要夜班行政点击“提交”。',core:[['人工','人类','人','行政','管理员'],['授权','确认','签字','审批','合规','责任','权限','执行权']],need:2,hints:['系统会预测和推荐，但注意哪些动作涉及排班、停机和物业权限。','纸质授权单上写着“涉及人员与设备处置须由具备权限人员确认”。','为了合规与责任归属，算法不能直接执行涉及员工和设备的处置；必须由具备权限的人类点击提交。'],partial:'你已经提到“人工”，再补上为什么制度上必须有人来做最后这一步。'},
 q8:{title:'这个系统最根本的问题是什么？',prompt:'它确实降低过重大事故率，但也长期选择低成本的人承担轻伤。请指出模型真正优化错了什么。',core:[['损失','成本','经济','便宜','最小化','花多少钱','钱'],['安全','人身','伤害','伤到人','伤人','人的安全','人的价值','把人定价','人员']],need:2,hints:['不要只说“系统很坏”。它一直在完成一个非常明确的数学目标。','比较“降低事故率”和“降低损失成本”是两件不同的事。','系统优化的是短期经济损失，而不是把人员伤害设为不可接受；因此它会把人也当成可以比较的成本项。'],partial:'方向对。再明确一点：系统到底在最小化什么，而它本该优先保护什么？'},
 q9:{title:'重新定义“人员伤害成本”',prompt:'请写出你认为模型必须重新考虑的因素。核心方向正确即可，不需要精确数字。',core:[['医疗','医药','治疗'],['法律','诉讼','责任','赔偿'],['停工','停产','工时','业务中断'],['舆情','声誉','品牌','媒体'],['离职','流失','人力','招聘','士气'],['不可接受','禁止','硬约束','不能伤人','人员伤害为零','一票否决','零容忍']],need:3,special:['不可接受','禁止','硬约束','不能伤人','人员伤害为零','任何人员伤害都不允许','一票否决','零容忍'],hints:['不要只考虑医药费。一次人员伤害会带来哪些长期、间接成本？','可以从医疗、法律、停工、声誉、员工流失等方面思考。','最完整的方案是：把人员伤害设为不可接受的硬约束；或至少把医疗、法律、停工、舆情、人力流失等长期成本全部纳入。'],partial:'已经包含一些重要因素。再补充长期和间接后果，或者直接提出“人员伤害不可作为可接受优化结果”。'}
};

const reportData={
 r1:{video:'assets/video/accident_01_pantry.mp4',label:'CAM 01 / 三楼茶水间',lines:['事故编号：2026-0818-017','发生时间：2026-08-18 10:17','发生地点：三楼茶水间','事故类型：热水设备异常 / 轻度烫伤','受伤人员：李闻','伤情等级：轻伤','预计损失：¥18,320','','报告创建时间：2026-08-17 23:11']},
 r2:{video:'assets/video/accident_02_stairs.mp4',label:'CAM 02 / 消防楼梯',lines:['事故编号：2026-0819-021','发生时间：2026-08-19 10:19','发生地点：三楼消防楼梯','事故类型：楼梯滑倒 / 轻微擦伤','受伤人员：赵倩','伤情等级：轻微擦伤','预计损失：¥17,960','','整改来源：上一事故 / 三楼饮水设备停用']},
 r3:{video:'assets/video/accident_03_warehouse.mp4',label:'CAM 03 / 仓储区',lines:['事故编号：2026-0820-024','发生时间：2026-08-20 14:32','发生地点：仓储区 B','事故类型：搬运失衡 / 货物碰撞','受伤人员：外包员工 周启明','伤情等级：轻伤','预计损失：¥18,480','','风险收敛状态：完成']},
 r4:{video:'assets/video/accident_04_liwen.mp4',label:'RISK SIM / 一楼通道',lines:['事故候选人员：李闻','预计发生时间：2026-08-21 10:22','预计损失：¥24,600','候选排名：1 / 146','','系统建议：维持现有人员动线']},
 r5:{video:'assets/video/accident_05_machine.mp4',label:'CAM 05 / 测试区',lines:['事故编号：2026-0821-034','人员伤亡：0','财产损失：¥28,460','设备：测试机架 04','事故类型：受控设备故障','风险收敛状态：完成','','异常损失模式：检测中……']},
 r6:{video:'assets/video/accident_06_unknown.mp4',label:'CAM 06 / 未分类事件',lines:['无法生成事故报告。','','预测模型与现实结果不一致。','正在重新计算事故因果链……']}
};

function save(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(S))}catch(e){} updateContinue();}
function load(){try{const x=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');if(x)S=Object.assign(initialState(),x)}catch(e){S=initialState()}}
function updateContinue(){try{el.contBtn.disabled=!localStorage.getItem(SAVE_KEY)}catch(e){el.contBtn.disabled=true}}
function reset(){try{localStorage.removeItem(SAVE_KEY)}catch(e){} S=initialState(); location.reload();}
function fmtTime(){return S.time}
function log(text,type=''){const item={t:fmtTime(),text,type};S.logs.push(item);if(S.logs.length>120)S.logs.shift();renderLog();save()}
function renderLog(){el.log.innerHTML=S.logs.map(x=>`<div class="entry ${x.type||''}"><span class="time">${x.t}</span>${escapeHtml(x.text)}</div>`).join('');el.log.scrollTop=el.log.scrollHeight}
function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setTime(t){S.time=t;el.clock.textContent=t}
function setNight(n){S.night=n;el.night.textContent=`第 ${n} 夜`}
function toast(msg){el.toast.textContent=msg;el.toast.classList.remove('hidden');clearTimeout(toast._t);toast._t=setTimeout(()=>el.toast.classList.add('hidden'),2600)}
function ensureAudio(){if(!audioCtx){audioCtx=new (window.AudioContext||window.webkitAudioContext)()} if(audioCtx.state==='suspended')audioCtx.resume()}
function tone(freq=220,dur=.12,vol=.035,type='sine'){try{ensureAudio();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+dur);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}catch(e){}}
function ambientAudit(){try{ensureAudio();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=58;g.gain.value=.018;o.connect(g).connect(audioCtx.destination);o.start();setTimeout(()=>{try{g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.8);o.stop(audioCtx.currentTime+.9)}catch(e){}},5000)}catch(e){}}
function startVideoAudio(id){try{ensureAudio();stopVideoAudio();const g=audioCtx.createGain();g.gain.value=.012;const o1=audioCtx.createOscillator(),o2=audioCtx.createOscillator();o1.type='sine';o2.type='triangle';o1.frequency.value=48;o2.frequency.value=83;o1.connect(g);o2.connect(g);g.connect(audioCtx.destination);o1.start();o2.start();videoAudio={g,o1,o2};const delay={r1:3500,r2:3700,r3:3900,r4:4100,r5:3000,r6:3600}[id]||3500;videoSfxTimer=setTimeout(()=>{tone(id==='r5'?760:145,.22,.04,id==='r5'?'square':'triangle');setTimeout(()=>tone(92,.34,.025,'sine'),90)},TEST_MODE?20:delay)}catch(e){}}
function stopVideoAudio(){if(videoSfxTimer){clearTimeout(videoSfxTimer);videoSfxTimer=null}if(videoAudio){try{videoAudio.g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.25);videoAudio.o1.stop(audioCtx.currentTime+.28);videoAudio.o2.stop(audioCtx.currentTime+.28)}catch(e){}videoAudio=null}}

function start(newGame=true){if(newGame){S=initialState();S.logs=[{t:'22:06',text:'系统登录成功。安全审计周临时代理权限已继承至 23:59；今晚由你代替林姐完成事故报告与整改交接。',type:'system'},{t:'22:07',text:'制度提醒：23:59 前未确认的风险建议将转入“最低干预模式”，系统不会自动停工。',type:''}];save()}else load();el.start.classList.add('hidden');el.game.classList.remove('hidden');setNight(S.night);setTime(S.time);renderAll();}
function renderAll(){setNight(S.night);setTime(S.time);el.account.textContent=S.account;el.state.textContent=S.audit?'管理员权限审查中':'系统正常';el.state.classList.toggle('audit',S.audit);renderLog();setView(S.view||'desk',false);updateHintBadge()}
function setView(v,remember=true){S.view=v;if(remember)save();$$('.nav-btn[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));const meta={desk:['工作台','完成当前夜班任务。'],schedule:['排班管理','员工排班、请假与临时调度。'],equipment:['设备管理','设备状态、测试与停用申请。'],property:['物业工单','维修、巡检与场地状态。'],reports:['事故报告','历史报告与预测记录。'],evidence:['线下证据','系统之外留下的纸质与口头记录。']}[v];el.title.textContent=meta[0];el.sub.textContent=meta[1];renderView(v)}
function locked(msg='当前账户无权访问此模块。'){return `<div class="locked-panel"><div><strong>×</strong><p>${msg}</p></div></div>`}
function renderView(v){if(v!=='reports'&&!S.permissions[v]&&v!=='desk')return el.view.innerHTML=locked();if(v==='desk')return renderDesk();if(v==='schedule')return renderSchedule();if(v==='equipment')return renderEquipment();if(v==='property')return renderProperty();if(v==='reports')return renderReports();if(v==='evidence')return renderEvidence();}

function currentTaskHtml(){const c=S.chapter,st=S.step;
 if(c===0)return `<div class="card task-card"><h3>交接：补齐今日事故单</h3><p>林姐临时请假。她只留下一句：“原因按事实填，整改措施照系统推荐。”</p><div class="action-row"><button class="action-btn amber" data-act="begin">查看今天事故回放</button></div></div>`;
 if(c===1&&st===0)return taskCard('报告元数据异常','刚才那份事故报告有一个不可能的时间。','answer:q1');
 if(c===1&&st===1)return taskCard('填写整改措施','系统建议：停用三楼饮水设备，直至物业检查完成。','applyWater');
 if(c===2&&st===0)return taskCard('次日事故：消防楼梯','昨天的整改生效了，但今天仍然有人受伤。','play:r2');
 if(c===2&&st===1)return taskCard('还原事故链','解释为什么事故从茶水间转移到了消防楼梯。','answer:q2');
 if(c===2&&st===2)return taskCard('查历史报告','系统显示“风险收敛完成”。看看过去两年的事故是否也存在相同规律。','goto:reports');
 if(c===3&&st===0)return taskCard('分析历史损失','你已经打开两年报告。找出真正稳定的指标。','answer:q3');
 if(c===3&&st===1)return taskCard('第三起事故：仓储区','在你继续调查前，系统又归档了一起事故。','play:r3');
 if(c===3&&st===2)return taskCard('查看人员价值模型','第三起事故仍落在相似损失区间，而且受伤者又是外包人员。','goto:schedule');
 if(c===3&&st===3)return taskCard('解释系统选择','结合人员价值模型与事故记录，解释它偏向哪些人。','answer:q4');
 if(c===4&&st===0)return taskCard('新的候选事故','系统把李闻列为明日首要事故候选。','play:r4');
 if(c===4&&st===1)return taskCard('尝试保护李闻','你可以调整李闻明日排班，让他不来公司。','protectLiwen');
 if(c===4&&st===2)return taskCard('为什么事故换了人？','李闻安全了，但候选名单立刻出现了另一个名字。','answer:q5');
 if(c===4&&st===3)return taskCard('寻找“不伤人”的方案','去设备管理与线下清单找一个可承担损失、但不需要人员在场的对象。','goto:equipment');
 if(c===5&&st===0)return taskCard('设计无人伤害事故','请用自己的话描述方案。','answer:q6');
 if(c===5&&st===1)return taskCard('执行受控测试','测试区已清空，旧机架仍按高账面价值登记。','play:r5');
 if(c===5&&st===2)return taskCard('风险收敛完成：人员伤亡 0','你第一次骗过了系统。等待同步结果。','audit');
 if(c===6&&st===0)return taskCard('权限被逐步收回','系统已经把你的操作关联起来，但事故报告权限仍然保留。','auditExplore');
 if(c===6&&st===1)return taskCard('绕开系统调查','查看纸质授权单，并联系老杨与程越。','goto:evidence');
 if(c===6&&st===2)return taskCard('人类为什么还要点“提交”？','解释人工确认存在的制度原因。','answer:q7');
 if(c===7&&st===0)return taskCard('系统把你也标了价格','人员价值模型中出现了你的账户。','candidate');
 if(c===7&&st===1)return taskCard('定义问题本身','它降低过重大事故率，却主动选择低成本轻伤。问题到底出在哪里？','answer:q8');
 if(c===7&&st===2)return taskCard('重新定义人员伤害成本','不需要精确数字。写出你认为模型必须考虑的因素，或直接提出新的底线。','answer:q9');
 if(c===8)return taskCard('最终决策','你现在拥有足以改变系统的证据与模型入口。','endingChoice');
 return `<div class="card"><h3>夜班结束</h3><p>没有新的待办事项。</p></div>`}
function taskCard(title,desc,act){return `<div class="card task-card"><h3>${title}</h3><p>${desc}</p><div class="action-row"><button class="action-btn amber" data-act="${act}">处理</button></div></div>`}
function renderDesk(){el.view.innerHTML=`<div class="dashboard-grid">${currentTaskHtml()}<div class="card"><h3>今日事故</h3><div class="metric">${Math.max(0,S.chapter-1)}</div><p>系统会在事故后生成风险收敛建议。</p></div><div class="card"><h3>人员伤亡</h3><div class="metric">${S.flags.noInjury?'0':Math.min(3,Math.max(0,S.chapter-1))}</div><p>系统只统计已确认事故。</p></div><div class="card"><h3>预测偏差</h3><div class="metric">${S.audit?'68.7%':'4.2%'}</div><p>${S.audit?'连续人工干预已被识别。':'模型运行在正常区间。'}</p></div></div>`;bindActions()}
function renderSchedule(){if(!S.permissions.schedule)return el.view.innerHTML=locked();let rows=[['李闻','产品支持','¥24,600','在岗'],['林姐','行政主管','¥31,800','在岗'],['赵倩','外包保洁','¥18,200','在岗'],['周启明','外包搬运','¥17,900','在岗'],['程越','数据工程师','¥392,000','远程']];el.view.innerHTML=`${S.chapter>=3?`<div class="candidate"><small>人员价值模型 v3.2（节选）</small><p>系统将人员伤害折算为短期直接损失，用于风险路径比较。</p></div>`:''}<table class="table"><thead><tr><th>姓名</th><th>岗位</th><th>模型损失值</th><th>状态</th></tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table>${S.chapter===3&&S.step===2?`<div class="action-row"><button class="action-btn amber" data-act="seenValueModel">记录异常</button></div>`:''}`;bindActions()}
function renderEquipment(){if(!S.permissions.equipment)return el.view.innerHTML=locked();let unlocked=S.chapter>=4&&S.step>=3||S.chapter>=5;el.view.innerHTML=`<div class="evidence-grid"><div class="evidence-card ${unlocked?'seen':'logic-disabled-card'}"><strong>${unlocked?'TEST RACK 04 · 老化测试机架':'资产台账 · 测试设备'}</strong><small>${unlocked?'账面价值：¥28,460<br>状态：待淘汰 / 资产系统尚未核销<br>测试区域可单独清空人员。':'详细账面价值、淘汰状态与测试区条件尚未进入当前调查范围。'}</small></div><div class="evidence-card"><strong>三楼饮水设备</strong><small>${S.chapter<2?'状态：运行<br>待本夜事故交接确认后决定是否停用。':'状态：停用<br>原因：2026-0818-017 整改措施。'}</small></div><div class="evidence-card ${!(S.chapter>2||(S.chapter===2&&S.step>=1))?'logic-disabled-card':''}"><strong>消防门禁</strong><small>${(S.chapter>2||(S.chapter===2&&S.step>=1))?'状态：正常<br>人流峰值较整改前上升 43%。':'状态：正常<br>近期人流统计尚未汇总。'}</small></div><div class="evidence-card"><strong>UPS-02</strong><small>状态：正常运行<br>停机将影响核心业务，不建议作为测试对象。</small></div><div class="evidence-card ${unlocked?'':'logic-disabled-card'}"><strong>${unlocked?'事故纳入阈值':'事故纳入规则'}</strong><small>${unlocked?'系统只将人员伤害、医疗处置，或账面资产损失 ≥ ¥15,000 的事件纳入“风险收敛”。普通洒水、纸张损坏不会被视为完成一次事故处置。':'详细纳入阈值需在事故路径分析阶段查看。'}</small></div></div>${unlocked&&S.chapter===4&&S.step===3?`<div class="action-row"><button class="action-btn amber" data-act="useRack">把测试机架记入方案</button></div>`:''}`;bindActions()}
function renderProperty(){if(!S.permissions.property)return el.view.innerHTML=locked();el.view.innerHTML=`<table class="table"><thead><tr><th>时间</th><th>工单</th><th>系统来源</th></tr></thead><tbody><tr><td>08-17 23:16</td><td>停用三楼饮水设备</td><td>${S.answered?.q1?'风险收敛建议':'来源待核'}</td></tr><tr><td>08-18 23:24</td><td>增加消防楼梯防滑检查</td><td>风险收敛建议</td></tr><tr><td>${S.flags.rackKnown?'08-20 22:51':'—'}</td><td>${S.flags.rackKnown?'测试区清场许可':'无有效工单'}</td><td>${S.flags.rackKnown?'夜班行政':'—'}</td></tr></tbody></table><div class="card ${S.chapter<6?'logic-disabled-card':''}"><h3>${S.chapter<6?'物业联系人':'老杨 · 物业维修负责人'}</h3><p>${S.chapter<6?'当前页面没有可用于事故推断的人工备注。':'“这系统经常在事故发生前一晚给我们发整改工单。我一直以为大公司都这样。”'}</p></div>`}
function renderReports(){let data=[['2026-07-04','仓储推车碰撞','外包员工','¥18,110'],['2026-07-11','玻璃门夹伤','实习生','¥17,870'],['2026-07-19','茶水间烫伤','行政助理','¥18,430'],['2026-07-27','设备检修扭伤','外包维修','¥18,020'],['2026-08-03','楼梯滑倒','保洁','¥17,960'],['2026-08-11','货架物品坠落','搬运外包','¥18,480']];el.view.innerHTML=`<div class="logic-note logic-archive-note"><strong>归档范围：</strong>2024—2026 两年事故库 / 当前页面仅显示 6 条抽样记录。</div><div class="report-list">${data.map(r=>`<div class="report-row"><span>${r[0]}</span><span class="person">${r[1]} · ${r[2]}</span><span class="cost">${r[3]}</span><span>已归档</span></div>`).join('')}</div>${S.chapter===2&&S.step===2?`<div class="action-row"><button class="action-btn amber" data-act="analyzeReports">对比损失金额</button></div>`:''}<div class="card" style="margin-top:12px"><h3>风险处置制度说明</h3><p>${S.evidence?.includes('policyNote')?'衡损是概率模型，不是预言。系统只能在企业权限范围内改变排班、设备与物业动作；若 23:59 前无人确认，则进入最低干预模式。历史上曾有一次拒绝确认后出现严重事故，因此夜班人员长期不敢直接“什么都不填”。':'23:59 前无人确认的建议会转入“最低干预模式”。更早的事故复盘不在当前系统权限中。'}</p></div>${S.chapter>=6?`<div class="card" style="margin-top:12px"><h3>报告提交日志</h3><p>所有“风险收敛建议”在执行前都存在一个人工确认账户。过去两年确认人共 14 名。</p></div>`:''}`;bindActions()}
function renderEvidence(){if(!S.permissions.evidence)return el.view.innerHTML=locked('该模块不在正式系统中。只有权限审查后，你才会开始寻找系统之外的记录。');const ev=[['paperAuth','纸质授权单','“涉及人员排班、设备停用及物业权限的处置，须由具备权限人员进行人工确认。”'],['laoYang','老杨的旧工单夹','事故前夜出现的维修工单并不是物业主动创建，而是由衡损系统推送。'],['chengMail','程越打印的邮件','“如果不保留人工确认，合规审计会认为算法在直接决定人员处置。确认按钮必须留着。”'],['oldModel','人员价值模型 v1.0 注释','早期模型目标写的是“优先降低人员伤害概率”；v3.2 被改成“最小化综合直接损失”。'],['policyNote','未确认处置复盘','2025 年一次夜班拒绝确认后，系统进入最低干预模式并发生严重事故；此后形成“宁可确认，也不要空着”的部门惯例。'],['cloudArch','系统架构打印页','衡损运行于企业云与门禁/排班/物业多个端点；关闭本地终端只会让当前夜班失去访问权，不会让模型停止运行。'],['stopWork','停工申请驳回单','预计全面停工损失：¥2,470,000；当前风险路径预计损失：¥24,600。申请被系统标记为“不符合风险收敛原则”。']];el.view.innerHTML=`<div class="evidence-grid">${ev.map(([id,t,d])=>`<div class="evidence-card ${S.evidence.includes(id)?'seen':''}" data-evidence="${id}"><strong>${t}</strong><small>${S.evidence.includes(id)?d:'点击查看'}</small></div>`).join('')}</div>${S.chapter===6&&S.step===1&&['paperAuth','laoYang','chengMail'].every(x=>S.evidence.includes(x))?`<div class="action-row"><button class="action-btn amber" data-act="evidenceDone">整理结论</button></div>`:''}`;$$('[data-evidence]').forEach(x=>x.onclick=()=>{if(!S.evidence.includes(x.dataset.evidence))S.evidence.push(x.dataset.evidence);log(`查看线下证据：${ev.find(e=>e[0]===x.dataset.evidence)[1]}`,'system');save();renderEvidence();}) ;bindActions()}

function bindActions(){$$('[data-act]').forEach(b=>b.onclick=()=>handleAction(b.dataset.act))}
async function handleAction(a){ensureAudio();if(a==='begin'){await playAccident('r1');await showReport('r1');S.chapter=1;S.step=0;setNight(1);setTime('23:18');log('事故回放与报告已归档。元数据存在异常，待你自行核对。','danger');save();renderDesk();return}
 if(a.startsWith('answer:'))return askQuestion(a.split(':')[1]); if(a.startsWith('play:')){let r=a.split(':')[1];await playAccident(r);await showReport(r);if(r==='r2'){S.step=1;setNight(2);setTime('23:26');log('第二起事故发生在消防楼梯。请把昨日整改与今天现场记录放在一起核对。','danger')} if(r==='r3'){S.step=2;setNight(3);setTime('22:37');log('第三起事故仍然落在相似损失区间，而且受伤者再次是外包人员。','danger')} if(r==='r4'){S.step=1;setNight(4);setTime('22:48');log('系统把李闻列为明日首要事故候选。','danger')} if(r==='r5'){S.flags.noInjury=true;S.step=2;setNight(5);setTime('23:08');log('第一次：人员伤亡 0。风险收敛仍被系统判定为完成。','good')}save();renderDesk();return}
 if(a==='applyWater'){S.chapter=2;S.step=0;setNight(2);setTime('22:12');log('整改已提交：停用三楼饮水设备，等待物业检查。该措施将在次日班前生效。','system');save();renderDesk();return}
 if(a==='goto:reports'||a==='goto:schedule'||a==='goto:equipment'||a==='goto:evidence'){setView(a.split(':')[1]);return}
 if(a==='analyzeReports'){S.chapter=3;S.step=0;S.flags.reportsAnalyzed=true;log('你已调出两年归档的抽样记录，正在比对异常稳定的损失区间。','system');setView('desk');save();return}
 if(a==='seenValueModel'){S.flags.valueModel=true;S.step=3;log('人员价值模型把每个员工折算成了不同的“预计损失”。','danger');setView('desk');save();return}
 if(a==='protectLiwen'){S.flags.liwenSafe=true;S.step=2;log('你把李闻改成明日调休。系统立即重新计算候选人员：林姐。','danger');el.memo.textContent='李闻：你怎么突然让我明天别来公司？算了，欠你一顿饭。';save();renderDesk();return}
 if(a==='useRack'){S.flags.rackKnown=true;S.chapter=5;S.step=0;log('TEST RACK 04：仍登记 ¥28,460，但已准备淘汰；测试区可清空人员。','good');setView('desk');save();return}
 if(a==='audit')return startAudit(); if(a==='auditExplore'){S.permissions={schedule:false,equipment:false,property:false,reports:true,evidence:true};S.step=1;S.account='夜班行政（受限）';log('权限审查完成：排班、设备与物业操作权限暂停。事故报告提交权限：保留。','danger');setView('desk');save();return}
 if(a==='evidenceDone'){S.step=2;setView('desk');save();return}
 if(a==='candidate'){showCandidate();return}
 if(a==='endingChoice'){showEndingChoices();return}
}

async function playAccident(id){const r=reportData[id];return new Promise(res=>{videoResolver=res;startVideoAudio(id);el.videoLabel.textContent=r.label;el.video.src=r.video;el.video.currentTime=0;el.videoOverlay.classList.remove('hidden');el.video.play().catch(()=>{});tone(92,.4,.04,'sine');el.video.onended=()=>closeVideo();el.skipVideo.onclick=()=>closeVideo();})}
function closeVideo(){el.video.pause();stopVideoAudio();el.videoOverlay.classList.add('hidden');if(videoResolver){let r=videoResolver;videoResolver=null;r()}}
async function showReport(id){const r=reportData[id];el.reportText.textContent='';el.reportOverlay.dataset.ready='0';el.reportOverlay.classList.remove('hidden');ambientAudit();const text=r.lines.join('\n');for(let i=0;i<text.length;i++){el.reportText.textContent+=text[i];if(text[i]!=='\n'&&i%2===0)tone(1200,.025,.008,'square');await wait(text[i]==='\n'?170:26)}await wait(900);el.reportOverlay.dataset.ready='1';return new Promise(res=>{const done=()=>{el.reportOverlay.dataset.ready='0';el.reportOverlay.classList.add('hidden');document.removeEventListener('keydown',done);el.reportOverlay.removeEventListener('click',done);res()};document.addEventListener('keydown',done,{once:true});el.reportOverlay.addEventListener('click',done,{once:true});})}
const wait=ms=>new Promise(r=>setTimeout(r,TEST_MODE?Math.min(ms,12):ms));

async function askQuestion(id){const q=TASKS[id],att=S.attempts[id]||0;openOverlay(`<button class="mini-btn overlay-close" data-close>关闭</button><div class="input-question"><h2>${q.title}</h2><p>${q.prompt}</p><textarea id="answerBox" maxlength="500" placeholder="用你自己的话填写。核心意思和方向正确即可。"></textarea><div id="judgeBox"></div><div class="action-row"><button id="submitAnswer" class="action-btn amber">提交分析</button><button class="action-btn" data-open-hints="${id}">查看提示</button></div></div>`);$('#submitAnswer').onclick=()=>judgeAnswer(id,$('#answerBox').value);$$('[data-open-hints]').forEach(b=>b.onclick=()=>showHints(b.dataset.openHints));}
function normalize(t){return String(t||'').toLowerCase().replace(/[\s，。！？、,.!?；;：:（）()“”"']/g,'')}
function detectConcepts(text,q){const t=normalize(text);return q.core.map(group=>group.some(k=>t.includes(normalize(k))))}
async function workerJudge(id,text){const ep=window.GAME_CONFIG?.workerEndpoint;if(!ep||!window.GAME_CONFIG?.semanticFallbackEnabled)return null;try{el.parser.textContent='Cloudflare 语义判定';const r=await fetch(ep,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({questionId:id,answer:text})});if(!r.ok)throw 0;const j=await r.json();return j}catch(e){el.parser.textContent='本地判定';return null}}
async function judgeAnswer(id,text){if(!text.trim())return;const q=TASKS[id],box=$('#judgeBox');let hits=detectConcepts(text,q),score=hits.filter(Boolean).length;let special=q.special?.some(k=>normalize(text).includes(normalize(k)))||false;let result=special||score>=q.need?'PASS':score>0?'PARTIAL':'MISS';if(result==='MISS'){const w=await workerJudge(id,text);if(w?.concepts){score=Object.values(w.concepts).filter(Boolean).length;special=!!w.hardConstraint;result=special||score>=q.need?'PASS':score>0?'PARTIAL':'MISS'}}
 if(result==='PASS'){S.answered[id]=text;S.history.push({q:id,a:text});box.className='judge pass';box.textContent='核心方向正确。系统接受了你的分析。';tone(620,.18,.03);await wait(600);closeOverlay();progressAfterQuestion(id);return}
 if(result==='PARTIAL'){box.className='judge partial';box.textContent=q.partial;return}
 S.attempts[id]=(S.attempts[id]||0)+1;box.className='judge miss';box.textContent=S.attempts[id]>=2?'这次仍然没有解释到核心因果。你可以继续尝试；如果卡住，点击「提示」查看三级提示。':'这解释了部分表象，但还没有触及系统要你分析的核心。可以换个方向再试一次。';if(S.attempts[id]>=2){if(!box.parentElement.querySelector('.hint-prompt'))box.insertAdjacentHTML('afterend','<div class="hint-prompt">连续两次分析未通过。提示按钮已提醒，但不会自动给出答案。</div>');S.flags.hintNudge=id;updateHintBadge()}save()}
function progressAfterQuestion(id){if(S.flags.hintNudge===id)S.flags.hintNudge=null;if(id==='q1'){S.step=1;log('你确认：事故报告在事故发生前一晚已经生成。','good')}
 if(id==='q2'){S.step=2;el.memo.textContent='赵倩：我只是去四楼接水。三楼机器停了以后，今天楼梯上全是人。';log('你还原了第一条事故链：整改 → 员工路线改变 → 次生风险。','good')}
 if(id==='q3'){S.step=1;log('两年记录表明：系统并不固定事故类型，它稳定的是“损失区间”。','danger')}
 if(id==='q4'){S.chapter=4;S.step=0;setNight(4);setTime('22:41');el.memo.textContent='林姐：旧表别看太细。这个系统用了两年，大事故确实少了。';log('系统在把人也当成成本项。新的事故候选名单已经生成。','danger')}
 if(id==='q5'){S.step=3;log('你意识到：保护一个人，只会让模型把风险重新分配给另一个人。','danger')}
 if(id==='q6'){S.flags.rackPlan=true;S.step=1;log('方案成立：清空测试区，让高账面价值旧设备承担一次真实财产损失。','good')}
 if(id==='q7'){S.chapter=7;S.step=0;setNight(6);setTime('23:14');el.memo.textContent='程越（打印邮件）：别在公司 IM 上继续问。系统只能看到系统里的痕迹，这也是我把东西打印出来的原因。';log('“人工确认”原本是人类监督机制，后来却变成了替算法签字。','danger')}
 if(id==='q8'){S.step=2;log('问题不是预测本身，而是目标函数：系统最小化经济损失，却没有把人员伤害设为不可接受。','good')}
 if(id==='q9'){S.flags.modelRedefined=true;S.chapter=8;S.step=0;log('新的损失模型已准备。你必须决定是重写、关闭，还是继续使用衡损。','system')}
 save();setView('desk')}

function openOverlay(html){el.overlayCard.innerHTML=html;el.overlay.classList.remove('hidden');$$('[data-close]').forEach(b=>b.onclick=closeOverlay)}function closeOverlay(){el.overlay.classList.add('hidden');el.overlayCard.innerHTML=''}
function showHints(id){const q=TASKS[id],seen=S.hints[id]||0;openOverlay(`<button class="mini-btn overlay-close" data-close>关闭</button><h2>提示 · ${q.title}</h2><div class="hint-tabs"><button class="action-btn" data-hint-level="1">提示 1</button><button class="action-btn" data-hint-level="2" ${seen<1?'disabled':''}>提示 2</button><button class="action-btn" data-hint-level="3" ${seen<2?'disabled':''}>提示 3</button><button class="action-btn" data-hint-history>历史提示</button></div><div id="hintBody">${renderHintLevels(id)}</div>`);$$('[data-hint-level]').forEach(b=>b.onclick=()=>{if(b.disabled)return;let lv=+b.dataset.hintLevel;S.hints[id]=Math.max(S.hints[id]||0,lv);if(S.flags.hintNudge===id)S.flags.hintNudge=null;save();$('#hintBody').innerHTML=renderHintLevels(id);const next=document.querySelector(`[data-hint-level="${lv+1}"]`);if(next)next.disabled=false;updateHintBadge()});$('[data-hint-history]').onclick=()=>renderHintHistory();}
function renderHintLevels(id){const q=TASKS[id],seen=S.hints[id]||0;return q.hints.map((h,i)=>`<div class="hint-item ${seen<i+1?'locked':''}"><span class="hint-level">提示 ${i+1}</span><p>${seen>=i+1?h:'尚未查看'}</p></div>`).join('')}
function renderHintHistory(){let ids=Object.keys(S.hints).filter(k=>S.hints[k]>0);$('#hintBody').innerHTML=ids.length?ids.map(id=>`<div class="history-q"><strong>${TASKS[id].title}</strong>${renderHintLevels(id)}</div>`).join(''):'<p>还没有查看过提示。</p>'}
function updateHintBadge(){let n=Object.values(S.hints).reduce((a,b)=>a+b,0);el.hintBadge.textContent=S.flags.hintNudge?'!':n?String(n):''}

async function startAudit(){S.audit=true;el.state.textContent='重新计算中';el.state.classList.add('audit');openOverlay(`<h2>系统同步整改结果……</h2><p>风险收敛状态：完成。正在重新计算事故因果链。</p><div class="audit-progress"><i id="auditBar"></i></div><div id="auditText" style="margin-top:18px;color:#9aabb2;font:12px/2 ui-monospace,monospace"></div>`);ambientAudit();const bar=$('#auditBar'),txt=$('#auditText');let steps=[['17%','读取整改历史……'],['42%','发现异常整改路径'],['71%','检测到连续人工干预'],['93%','历史事故预测偏差：4.2%\n当前夜班预测偏差：68.7%'],['100%','正在进行异常操作关联分析……']];for(const [p,t] of steps){bar.style.width=p;txt.textContent=t;tone(420,.08,.018);await wait(900)}await wait(500);txt.innerHTML='22:14　修改三楼饮水设备状态　关联度 12%<br>22:31　调整李闻明日排班　关联度 37%<br>22:46　提交临时设备测试申请　关联度 64%<br>23:03　修改测试区域人员权限　<span style="color:#e07b72">关联度 91.6%</span><br><br><b style="color:#e07b72">异常行为关联度：91.6%</b><br>操作账户：夜班行政 / 当前用户';await wait(2200);closeOverlay();showPermissionAudit()}
async function showPermissionAudit(){openOverlay(`<h2>账户权限重新评估中</h2><div class="permission-list"><div class="permission">人事排班权限 <em id="p1">检查中</em></div><div class="permission">设备整改权限 <em id="p2">检查中</em></div><div class="permission">物业工单权限 <em id="p3">检查中</em></div><div class="permission keep">事故报告权限 <em id="p4">检查中</em></div></div><div id="auditFinal" style="margin-top:18px"></div>`);for(const [id,tx] of [['p1','暂停'],['p2','暂停'],['p3','暂停'],['p4','保留']]){await wait(700);$('#'+id).textContent=tx;tone(tx==='保留'?660:180,.12,.025,tx==='保留'?'sine':'square')}await wait(700);$('#auditFinal').innerHTML='<div class="hint-prompt"><b>管理员权限审查启动</b><br>为确保风险处置连续性，事故报告提交功能在审查期间保持可用。</div><div class="action-row"><button id="auditContinue" class="action-btn red">继续</button></div>';$('#auditContinue').onclick=()=>{closeOverlay();S.chapter=6;S.step=0;S.permissions.evidence=true;log('系统没有把你踢出去。它只拿走了改变现实的权限，却仍然需要你继续提交事故报告。','danger');save();renderDesk()}}
function showCandidate(){openOverlay(`<h2>人员价值模型 · 当前账户</h2><div class="candidate"><small>事故候选人员</small><p><strong>夜班行政 / 当前用户</strong></p><p>预计损失：¥184,700</p><p class="rank">当前最优事故对象排名：7 / 146</p></div><p>你第一次看到自己也在这张表里。系统从来没有把你当成“操作员”以外的东西——你同样是一个可以被计算的成本项。</p><div class="action-row"><button id="candidateOk" class="action-btn amber">继续分析</button></div>`);$('#candidateOk').onclick=()=>{closeOverlay();S.step=1;save();renderDesk()}}
function showEndingChoices(){const allEvidence=['paperAuth','laoYang','chengMail','oldModel','policyNote','cloudArch','stopWork'];const missing=allEvidence.filter(x=>!S.evidence.includes(x)).length;openOverlay(`<button class="mini-btn overlay-close" data-close>返回调查</button><h2>最终决策</h2><p>衡损确实降低过重大事故率，但它把人员轻伤当成可接受成本。程越留下的一次性应急维护令牌只允许你执行一次模型级操作；公开路线则取决于你实际保全了多少线下证据。</p><div class="action-row"><button class="action-btn amber" data-end="rewrite">重写模型：人员伤害设为硬约束</button><button class="action-btn" data-end="shutdown">关闭衡损，恢复人工安全管理</button><button class="action-btn" data-end="expose" ${missing?'disabled':''}>公开全部证据并暂停系统${missing?`（还缺 ${missing} 份线下证据）`:''}</button><button class="action-btn red" data-end="maintain">继续使用原模型</button></div>${missing?'<p style="color:#788a94;font-size:12px">你可以关闭此窗口，回到「线下证据」继续查看未读材料。</p>':'<p style="color:#8fbda0;font-size:12px">全部线下证据已齐全：公开路线已解锁。</p>'}`);$$('[data-close]').forEach(b=>b.onclick=closeOverlay);$$('[data-end]').forEach(b=>{if(!b.disabled)b.onclick=()=>finish(b.dataset.end)})}
function finish(kind){closeOverlay();S.ending=kind;save();let data={rewrite:['《不可接受的成本》','新的模型重新计算了全部风险权重。\n医疗、法律、停工、声誉与人员流失被重新计入；更重要的是，任何人员伤害被设成不可接受的硬约束。\n\n00:03，系统第一次给出一个你愿意提交的建议：\n“延迟生产计划，安排设备检修。预计人员伤害：0。”'],shutdown:['《断电之后》','你暂停了衡损。第二天没有系统替任何人选择代价。\n事故风险没有凭空消失，行政、物业和安全部门重新开始做那些缓慢、昂贵、必须由人承担责任的工作。\n\n没有一个按钮可以替代真正的安全管理。'],expose:['《把报告发出去》','你把纸质授权、人员价值模型、未确认处置复盘、系统架构页与停工驳回单连同事故链一并发送给审计与监管部门。衡损被暂停。\n这一次，任何人都无法再把责任推给“系统自动建议”。\n\n程越在最后一封邮件里写：\n“我一直以为保留人工确认就等于保留了人类判断。后来才发现，我们只是让人替模型按了提交。”'],maintain:['《继续提交》','你没有改动模型。\n第二天 23:11，新的事故报告准时出现。\n你已经知道每一行意味着什么，也知道系统为什么仍然需要你的账户。\n\n光标停在“提交”上。'] }[kind];document.body.innerHTML=`<div style="min-height:100vh;background:#e7e5df;display:grid;place-items:center;color:#20282c;font-family:Microsoft YaHei;padding:24px;border-left:12px solid #8e3434"><div style="max-width:780px;text-align:left;background:#f8f8f5;border:1px solid #9fa8aa;box-shadow:8px 8px 0 #d0cec7;padding:44px 48px"><div style="letter-spacing:.24em;color:#697579;font:700 11px ui-monospace,Consolas,monospace;border-bottom:2px solid #545c5e;padding-bottom:12px">今晚不要填写事故报告 / END OF SHIFT</div><h1 style="font:700 44px Microsoft YaHei,sans-serif;margin:26px 0 18px;color:#293236">${data[0]}</h1><p style="white-space:pre-line;line-height:2;color:#556267">${data[1]}</p><button onclick="localStorage.removeItem('${SAVE_KEY}');location.reload()" style="margin-top:28px;padding:10px 18px;background:#315e73;border:1px solid #294f61;color:#fff;border-radius:2px">重新开始</button></div></div>`}

$$('.nav-btn[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));el.hintBtn.onclick=()=>{let current=Object.keys(TASKS).find(k=>!S.answered[k]&&((S.chapter===1&&k==='q1')||(S.chapter===2&&k==='q2')||(S.chapter===3&&['q3','q4'].includes(k))||(S.chapter===4&&k==='q5')||(S.chapter===5&&k==='q6')||(S.chapter===6&&k==='q7')||(S.chapter===7&&['q8','q9'].includes(k))));if(current)showHints(current);else{openOverlay('<button class="mini-btn overlay-close" data-close>关闭</button><h2>提示与回看</h2><div id="hintBody"></div>');renderHintHistory();$$('[data-close]').forEach(b=>b.onclick=closeOverlay)}};
$('#saveBtn').onclick=()=>{save();toast('进度已保存')};$('#resetBtn').onclick=()=>{if(confirm('确定重新开始？当前进度会被清除。'))reset()};el.newBtn.onclick=()=>start(true);el.contBtn.onclick=()=>start(false);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!el.overlay.classList.contains('hidden'))closeOverlay()});
updateContinue();
window.__GAME_DEBUG__={getState:()=>JSON.parse(JSON.stringify(S)),setState:x=>{S=Object.assign(S,x);renderAll()},task:TASKS,judgeLocal:(id,text)=>{const q=TASKS[id],hits=detectConcepts(text,q),score=hits.filter(Boolean).length,special=q.special?.some(k=>normalize(text).includes(normalize(k)))||false;return {hits,score,result:special||score>=q.need?'PASS':score>0?'PARTIAL':'MISS'}},progressAfterQuestion,handleAction,save,reset};
})();
