(() => {
'use strict';
const START=22*60+47, LOOP_END=23*60+17, SAVE_KEY='game2317_save_v2', OLD_SAVE='game2317_save_v1';
const ACTIONS=new Set(['INSPECT','MOVE','TALK','CALL','MESSAGE','USE','PLACE','HIDE','FOLLOW','WAIT','TEST','INFER','UNSUPPORTED']);
const TARGETS=new Set(['FOYER','LIVING','BEDROOM','KITCHEN','BATHROOM','CORRIDOR_7F','ROOM_704','STAIRCASE','ELEVATOR','ROOFTOP','LOBBY','PROPERTY_OFFICE','CONVENIENCE_STORE','ZHOU_YAN','FENG_CHUAN','MAINTENANCE_WORKER','GUARD_ZHAO','DU_COLLEAGUE','POLICE','SMOKE_DETECTOR','PHONE','CAMERA','KEY','EVIDENCE','DOOR_703','DOOR_704','SCENE','']);
const LOCATIONS={FOYER:{name:'703 · 玄关',img:'assets/foyer.jpg'},LIVING:{name:'703 · 客厅',img:'assets/living.jpg'},BEDROOM:{name:'703 · 卧室',img:'assets/bedroom.jpg'},KITCHEN:{name:'703 · 厨房',img:'assets/kitchen.jpg'},BATHROOM:{name:'703 · 卫生间',img:'assets/bathroom.jpg'},CORRIDOR_7F:{name:'7楼 · 走廊',img:'assets/corridor.jpg'},ROOM_704:{name:'704 · 房间',img:'assets/room704.jpg'},STAIRCASE:{name:'消防楼梯',img:'assets/staircase.jpg'},ELEVATOR:{name:'7楼 · 电梯口',img:'assets/corridor.jpg'},ROOFTOP:{name:'天台',img:'assets/rooftop.jpg'},LOBBY:{name:'一楼大厅',img:'assets/lobby.jpg'},PROPERTY_OFFICE:{name:'物业值班室',img:'assets/property.jpg'},CONVENIENCE_STORE:{name:'小区便利店',img:'assets/store.jpg'}};
const TIMELINE=[[22*60+47,'一名物业外包维修人员进入小区（身份未确认）','feng_arrival'],[22*60+52,'704门口出现维修人员（未确认）','feng_knock'],[22*60+56,'704发生争执（未确认）','argument'],[23*60+3,'周妍处理一份重要资料（未确认）','backup'],[23*60+8,'704里的人离开（未确认）','leave704'],[23*60+11,'有人进入天台（未确认）','rooftop_move'],[23*60+16,'“703，帮我报警。”','help_message'],[23*60+17,'██████','death']];
const KNOWLEDGE_LABELS={LOOP:'23:17之后，时间会回到22:47。',HELP:'23:16，一个陌生号码会给你发来“703，帮我报警”的求救消息。',ZHOU:'704住户叫周妍，她今晚确实在家。',REPAIRMAN:'22:50前后，一名物业外包维修人员会来到7楼。',FENG:'这名维修员叫冯川，是物业外包人员。',ARGUMENT:'22:56前后，704会发生争执。',MASTER_KEY:'那名维修员身上有可以打开704的物业维修钥匙。',CAMERA:'704的烟雾报警器里藏着偷拍设备。',EVIDENCE_LOCATION:'周妍把偷拍视频证据备份在卫生间吊顶里的存储卡。',ROOFTOP:'23:11前后，周妍和那名维修员会去天台。',FENG_MOTIVE:'那名维修员知道周妍发现了偷拍设备，他今晚很可能是来拿回证据的。',POLICE_NEED_PROOF:'没有明确证据时，提前报警只会让物业先接到核实电话。',CONFESSION_ROUTE:'用证据诈那名维修员，并同时录音，可以逼他说漏嘴。',TRUE_CAUSE:'循环似乎与周妍23:17的死亡有关，而不是与玩家是否离开小区有关。'};
const HINTS={
  START:['先按普通人的习惯行动，不必一开始就把一切当案件。','你可以先看看家里、手机和门外；第一轮允许什么都来不及。','如果没有新信息，就让时间走到23:17。循环本身就是第一条关键事实。'],
  FIND_ZHOU:['23:16的求救只写了“703”，先想想谁最可能知道你的房号。','下一轮可以在23:16之前接触隔壁704，或者给704的人发消息。','提前敲704的门、问704住户，确认求救者就是周妍。'],
  FIND_FENG:['别只盯着704屋内。今晚还有谁会进入这栋楼？','22:50前后，一楼大厅、七楼走廊和消防楼梯都可能看到维修人员。','去一楼问门卫或查物业维修登记，可以确认维修员姓名。'],
  FIND_CAMERA:['“线路维修”这个身份为什么方便进入704？想想哪些设备看起来像维修对象。','进入704后，不要只搜抽屉；注意天花板上的设备。','检查704的烟雾报警器。'],
  FIND_EVIDENCE:['发现偷拍设备还不够，周妍自己是否保存了能交给警方的证据？','她不信任你。利用循环中只有你知道的时间或偷拍细节提高信任。','告诉周妍你知道23:16求救或偷拍设备；她会告诉你证据在卫生间吊顶。'],
  FIND_ROUTE:['证据位置明确后，补齐23:08之后的路线。','可以跟踪维修员、守消防楼梯，或在七楼走廊观察704离开的人。','23:08到23:12之间盯住消防楼梯/维修员，就能确认天台路线。'],
  ENDGAME:['救下周妍只是第一层目标。想想什么能让警方真正处理冯川。','最好同时准备：可交付证据、提前警告周妍、有效报警，以及能锁定冯川的录音/供述。','拿到吊顶存储卡后报警；提前警告周妍；打开录音并用偷拍视频/证据试探维修员，使其说漏嘴。']
};
function baseState(){return{version:2,loop:1,time:START,location:'FOYER',meta:{knowledge:[],timelineKnown:[],totalActions:0,perfectAttempts:0,hints:{}},loopState:{zhouTrust:0,zhouTrustSources:[],fengSuspicion:0,policeCalled:false,policeETA:null,evidence:false,recording:false,confession:false,warnedZhou:false,zhouSafe:false,fengDetained:false,rooftopBlocked:false,hasMaintenanceKey:false,phoneBattery:36,visited:[],eventSeen:[],falseEndingTriggered:false,falseRepairReported:false}}}
function sanitizeState(raw){const b=baseState();if(!raw||typeof raw!=='object')return b;const s={...b,...raw};s.meta={...b.meta,...(raw.meta||{})};s.loopState={...b.loopState,...(raw.loopState||{})};s.meta.knowledge=Array.isArray(s.meta.knowledge)?s.meta.knowledge.filter(k=>KNOWLEDGE_LABELS[k]):[];s.meta.timelineKnown=Array.isArray(s.meta.timelineKnown)?s.meta.timelineKnown:[];s.meta.hints=s.meta.hints&&typeof s.meta.hints==='object'?s.meta.hints:{};s.loopState.zhouTrustSources=Array.isArray(s.loopState.zhouTrustSources)?s.loopState.zhouTrustSources.filter(x=>x==='HELP'||x==='CAMERA'):[];s.loop=Math.max(1,Number(s.loop)||1);s.time=Math.max(START,Math.min(LOOP_END,Number(s.time)||START));if(!LOCATIONS[s.location])s.location='FOYER';s.version=2;return s}
const $=s=>document.querySelector(s);const els={clock:$('#clock'),loop:$('#loopBadge'),sceneImg:$('#sceneImg'),sceneWrap:$('#sceneWrap'),sceneLabel:$('#sceneLabel'),sceneNote:$('#sceneNote'),peopleNote:$('#peopleNote'),knowledgeCount:$('#knowledgeCount'),hintStageLabel:$('#hintStageLabel'),focusName:$('#focusName'),log:$('#log'),input:$('#commandInput'),send:$('#sendBtn'),objective:$('#objective'),hotspots:$('#hotspots'),parser:$('#parserStatus'),ideas:$('#ideas'),flash:$('#eventFlash'),sound:$('#soundBtn')};
function load(){try{const raw=localStorage.getItem(SAVE_KEY)||localStorage.getItem(OLD_SAVE);return raw?sanitizeState(JSON.parse(raw)):null}catch(e){return null}}let state=load()||baseState();
function save(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));localStorage.removeItem(OLD_SAVE)}catch(e){}}
function clearSave(){try{localStorage.removeItem(SAVE_KEY);localStorage.removeItem(OLD_SAVE)}catch(e){}}
function fmt(m){return`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function hasK(k){return state.meta.knowledge.includes(k)}function addK(k,q=false){if(!hasK(k)&&KNOWLEDGE_LABELS[k]){state.meta.knowledge.push(k);if(!q)log(`【新的事实】 ${KNOWLEDGE_LABELS[k]}`,'clue')}}function knowTimeline(k){if(!state.meta.timelineKnown.includes(k))state.meta.timelineKnown.push(k)}function grantZhouTrust(source,amount){if(!state.loopState.zhouTrustSources.includes(source)){state.loopState.zhouTrustSources.push(source);state.loopState.zhouTrust+=amount}}
function log(text,type='normal',withTime=true){const d=document.createElement('div');d.className=`entry ${type}`;d.innerHTML=(withTime?`<span class="time">${fmt(state.time)}</span>`:'')+esc(text).replace(/\n/g,'<br>');els.log.appendChild(d);els.log.scrollTop=els.log.scrollHeight}

// --- audio ---
let audioCtx=null,audioEnabled=localStorage.getItem('g2317_sound')!=='off',ambTimer=null;
function ensureAudio(){if(!audioEnabled)return null;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}catch(e){return null}}
function tone(f=180,d=.12,g=.015,delay=0,type='sine'){const c=ensureAudio();if(!c)return;const o=c.createOscillator(),v=c.createGain();o.type=type;o.frequency.value=f;v.gain.setValueAtTime(.0001,c.currentTime+delay);v.gain.exponentialRampToValueAtTime(g,c.currentTime+delay+.01);v.gain.exponentialRampToValueAtTime(.0001,c.currentTime+delay+d);o.connect(v).connect(c.destination);o.start(c.currentTime+delay);o.stop(c.currentTime+delay+d+.03)}
function noise(d=.18,g=.006,hz=500,delay=0){const c=ensureAudio();if(!c)return;const b=c.createBuffer(1,Math.floor(c.sampleRate*d),c.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*(1-i/a.length);const s=c.createBufferSource(),f=c.createBiquadFilter(),v=c.createGain();s.buffer=b;f.type='bandpass';f.frequency.value=hz;v.gain.value=g;s.connect(f).connect(v).connect(c.destination);s.start(c.currentTime+delay)}
function sfx(kind){if(!audioEnabled)return;if(kind==='elevator'){tone(880,.08,.012);tone(1320,.09,.009,.08)}else if(kind==='phone'){tone(155,.07,.012,0,'square');tone(155,.07,.012,.12,'square')}else if(kind==='door'){tone(150,.05,.012);noise(.1,.008,1200,.03)}else if(kind==='foot'){tone(78,.08,.008);noise(.08,.004,220,.06)}else if(kind==='wind'){noise(.7,.006,260)}else if(kind==='fridge'){tone(58,.45,.004);tone(116,.25,.002,.05)}else if(kind==='knock'){tone(95,.05,.01);tone(90,.05,.009,.14)}else if(kind==='pipe'){tone(112,.18,.006);tone(82,.25,.004,.1)}else if(kind==='fluorescent'){tone(100,.5,.0018);tone(200,.32,.0012,.04)}else if(kind==='tv'){noise(.35,.0025,1450);tone(220,.18,.0015,.12)}else if(kind==='fan'){noise(.5,.0032,340);tone(52,.45,.0018)}else if(kind==='city'){noise(.55,.0026,210);tone(74,.28,.0013,.1)}}
function scheduleAmbient(){clearTimeout(ambTimer);if(!audioEnabled)return;ambTimer=setTimeout(()=>{const l=state.location,r=Math.random();if(l==='ROOFTOP')sfx(r<.72?'wind':'city');else if(l==='KITCHEN')sfx(r<.55?'fridge':r<.82?'pipe':'city');else if(l==='CORRIDOR_7F'||l==='ELEVATOR')sfx(r<.38?'elevator':r<.74?'foot':'fluorescent');else if(l==='LOBBY')sfx(r<.3?'elevator':r<.58?'foot':r<.82?'fluorescent':'tv');else if(l==='PROPERTY_OFFICE')sfx(r<.45?'fluorescent':r<.72?'fan':'tv');else if(l==='STAIRCASE')sfx(r<.72?'foot':'fluorescent');else if(l==='BATHROOM')sfx(r<.68?'pipe':'fan');else if(l==='ROOM_704')sfx(r<.36?'pipe':r<.7?'tv':'foot');else if(l==='LIVING'||l==='BEDROOM'||l==='FOYER')sfx(r<.3?'pipe':r<.62?'foot':r<.82?'tv':'city');else sfx('foot');scheduleAmbient()},14000+Math.random()*18000)}
function setSound(v){audioEnabled=!!v;localStorage.setItem('g2317_sound',audioEnabled?'on':'off');els.sound.textContent=`声音：${audioEnabled?'开':'关'}`;if(audioEnabled){ensureAudio();scheduleAmbient()}else clearTimeout(ambTimer)}

function hintStageLabel(key){return({START:'起始',FIND_ZHOU:'确认周妍',FIND_FENG:'锁定冯川',FIND_CAMERA:'寻找偷拍设备',FIND_EVIDENCE:'锁定证据',FIND_ROUTE:'补齐路线',ENDGAME:'终局布置'}[key]||'起始')}
function currentFocus(){if(hasK('ROOFTOP'))return'阻止23:17';if(hasK('CAMERA')&&!hasK('ROOFTOP'))return'周妍 / 冯川';if(hasK('FENG'))return'冯川';if(hasK('ZHOU'))return'周妍';return'无'}
function sceneNotes(location){const notes={FOYER:{scene:'703的门厅、餐桌和小厨房挤在同一片空间里，像被生活磨得很熟悉的出租屋。',people:'你刚下班回家。此刻谁也没有向你求助，整晚看起来再普通不过。'},LIVING:{scene:'客厅狭长而温暖，窗外对楼的灯一格一格亮着，像城市里最常见的夜生活。',people:'这里是你每一轮重新开始的锚点：普通、安静，也因此更衬得23:17格外异常。'},BEDROOM:{scene:'卧室收拾得不算整齐，床头纸巾、衣柜和行李箱让“租住感”很强。',people:'这是最私人也最安全的地方，但你已经知道安全感会在23:17被强行打断。'},KITCHEN:{scene:'台面上留着锅具和水杯，厨房与玄关相连，构成这套小公寓最真实的生活痕迹。',people:'日常感越强，循环就越不像超自然奇观，而像突然刺入现实的一根钉子。'},BATHROOM:{scene:'卫生间狭小但干净，毛巾和洗漱用品都带着有人认真生活过的气息。',people:'当你知道704卫生间吊顶藏着证据后，这个空间也开始变得不只是日常。'},CORRIDOR_7F:{scene:'703、704、705和电梯口被放在同一视线里，整层楼的空间关系一眼就能读明白。',people:hasK('FENG')?'冯川最容易在这里现身；周妍也会从704出来走向楼梯。':'704门前的动静、维修员的停留和23:08后的离开路线，都会从这里暴露出来。'},ROOM_704:{scene:'704是同一栋楼里的另一套小公寓：更柔和、更有人长期独居留下的整理痕迹。',people:hasK('EVIDENCE_LOCATION')?'周妍终于愿意把秘密告诉你。这个房间不只是案发现场，也是她努力自保的地方。':hasK('ZHOU')?'你已经确认这里住的是周妍，但她今晚为什么紧张，仍需要从她愿意透露的事实里慢慢判断。':'你还不知道704住户的姓名。这里只能确认有人长期独居，而且今晚屋内的气氛明显不太正常。'},STAIRCASE:{scene:'消防楼梯狭窄冰冷，转角和门洞让它天然适合躲藏与跟踪。',people:'冯川上楼、周妍离开、通往天台的路线，都会在这里短暂交汇。'},ROOFTOP:{scene:'屋面潮湿空旷，水箱、空调外机和低矮女儿墙让这里更像真实居民楼的天台，而不是奇观景点。',people:'这里承接的是整条时间线最后几分钟的重量：谁上来、谁活下来、循环会不会结束。'},LOBBY:{scene:'一楼大厅有电梯、公告栏、信箱和通向值班室的过道，属于一眼就认得出的老居民楼公共区域。',people:'老赵通常在一楼活动。谁进楼、谁刷门禁、谁自称来维修，都能从这里得到第一层确认。'},PROPERTY_OFFICE:{scene:'值班室很小，监控屏、登记本和老式电话比任何对白都更能说明这里的工作逻辑。',people:'老赵不是功能性NPC，他熟悉每个住户和外包人员，是这栋楼最接近“见证者”的人。'},CONVENIENCE_STORE:{scene:'便利店灯光发白，像和这栋楼共享同一种深夜疲惫。',people:'这里能暂时把你从案件里抽离出来，也提醒你这一切发生在再普通不过的生活半径内。'}};return notes[location]||{scene:'这里暂时没有新的环境信息。',people:'目前没有新的相关人物线索。'}}

function updateObjective(){let t='先回家。明天 8:30 还要上班。';if(hasK('LOOP')&&!hasK('ZHOU'))t='你有30分钟。先确认23:16那条求救消息来自谁。';else if(hasK('ZHOU')&&!hasK('FENG'))t='弄清今晚谁会去704，以及他为什么出现。';else if(hasK('FENG')&&!hasK('CAMERA'))t='冯川和704有关。找到他真正想拿走的东西。';else if(hasK('CAMERA')&&!hasK('EVIDENCE_LOCATION'))t='偷拍设备不是全部。周妍应该还有能证明这一切的证据。';else if(hasK('EVIDENCE_LOCATION')&&!hasK('ROOFTOP'))t='掌握证据之后，弄清23:17之前发生的最后几分钟。';else if(hasK('ROOFTOP'))t='你已经知道今晚会发生什么。想办法让23:17之后出现23:18。';els.objective.textContent=t}
function updateUI(){els.clock.textContent=fmt(state.time);els.loop.textContent=`第 ${state.loop} 轮`;const l=LOCATIONS[state.location]||LOCATIONS.FOYER;els.sceneImg.src=l.img;els.sceneLabel.textContent=(state.location==='ROOM_704'&&hasK('ZHOU'))?'704 · 周妍的房间':l.name;els.sceneWrap.dataset.location=state.location;const notes=sceneNotes(state.location);if(els.sceneNote)els.sceneNote.textContent=notes.scene;if(els.peopleNote)els.peopleNote.textContent=notes.people;if(els.knowledgeCount)els.knowledgeCount.textContent=`${state.meta.knowledge.length}/${Object.keys(KNOWLEDGE_LABELS).length}`;if(els.hintStageLabel)els.hintStageLabel.textContent=hintStageLabel(hintStage());if(els.focusName)els.focusName.textContent=currentFocus();renderHotspots();updateObjective();save();setSound(audioEnabled)}
function result(ok,text,cost){return{ok,text,cost}}
function moveTo(target){if(!LOCATIONS[target])return result(false,'你不知道那个地方在哪里。',0);const costs={FOYER:1,LIVING:1,BEDROOM:1,KITCHEN:1,BATHROOM:1,CORRIDOR_7F:1,ELEVATOR:1,STAIRCASE:2,ROOM_704:2,LOBBY:3,PROPERTY_OFFICE:3,CONVENIENCE_STORE:4,ROOFTOP:3};if(target==='ROOM_704'&&state.time>=22*60+52&&state.time<23*60+8&&!state.loopState.hasMaintenanceKey&&state.loopState.zhouTrust<2)return result(false,'704的门关着。里面的人显然不打算随便开门。',1);if(target==='ROOM_704'&&state.time>=23*60+8&&!state.loopState.hasMaintenanceKey)return result(false,'704已经锁上了。没有钥匙，你进不去。',1);if(target==='ROOFTOP'&&!hasK('ROOFTOP')&&state.time<23*60+8)return result(false,'你知道楼顶有天台，但现在没有理由过去。消防门也锁着。',1);state.location=target;if(!state.loopState.visited.includes(target))state.loopState.visited.push(target);if(target==='CORRIDOR_7F'||target==='ELEVATOR')sfx('elevator');if(target==='STAIRCASE')sfx('foot');if(target==='ROOFTOP')sfx('wind');return result(true,arrivalText(target),costs[target]||2)}
function arrivalText(t){const m=state.time;if(t==='CORRIDOR_7F'){if(m>=22*60+51&&m<=22*60+54){addK('REPAIRMAN');knowTimeline('feng_knock');return'你来到七楼走廊。704门前站着一个穿深色维修服的男人，工具箱放在脚边。他看了你一眼，没有打招呼。你还不知道他是谁。'}if(m>=22*60+55&&m<=23*60+7)return'七楼走廊很安静。704门关着，门后偶尔传来压低的说话声。';if(m>=23*60+8&&m<=23*60+11){addK('ROOFTOP');knowTimeline('leave704');return'你刚走到走廊，就看见周妍和那个维修员一前一后往消防楼梯走。周妍没有回头。'}return'七楼走廊亮着过分苍白的灯。703、704、705三扇门安静地排在一起。'}if(t==='STAIRCASE'){if(m>=22*60+49&&m<=22*60+55){addK('REPAIRMAN');addK('MASTER_KEY');return'你躲在消防门后。维修员从下面上来。工具箱旁，一串物业钥匙撞在一起，其中一把贴着“704”。'}if(m>=23*60+9&&m<=23*60+12){addK('ROOFTOP');return'上方传来脚步声。周妍和维修员正在往天台去。'}return'消防楼梯比走廊冷。楼下的声控灯一层层熄灭。'}if(t==='ROOM_704')return'704里没有任何“悬疑片式”的夸张布置：沙发旁摊着抱枕，书桌亮着小台灯，窗边留着还没收起的杯子。越普通，越说明周妍原本只是想把今晚熬过去。';if(t==='ROOFTOP')return'天台潮湿发冷，外机和水箱把空间切成几块。护栏外是压得很低的城市夜色，这里就是23:17之前最后会有人到达的地方。';if(t==='PROPERTY_OFFICE')return'值班室里亮着惨白日光灯，监控画面、登记本和座机都还开着。老赵抬眼看你，像是已经准备好回答今晚的进出记录。';if(t==='LOBBY')return'一楼大厅贴着公告栏，信箱和电梯都在视线内。这个位置足以把今晚谁进过楼、谁往值班室去，都看得很清楚。';if(t==='CONVENIENCE_STORE')return'便利店还开着。冷柜嗡嗡作响，店员低头刷手机。23:17似乎离这里很远。';return`你来到${LOCATIONS[t].name}。`}
function inspect(target){const L=state.location;if(target==='SMOKE_DETECTOR'){if(L!=='ROOM_704')return result(false,'这里没有你想检查的那个烟雾报警器。',0);addK('CAMERA');addK('FENG_MOTIVE');return result(true,'你拧下烟雾报警器外壳。里面藏着一个朝向客厅的小型镜头和存储模块，胶带重新贴过，手法熟练得像做过不止一次。它显然不是消防设备的一部分。',2)}if(target==='DOOR_704'||(target==='DOOR'&&L==='CORRIDOR_7F')){if(L!=='CORRIDOR_7F')return result(false,'你得先到704门口。',0);sfx('door');if(state.time>=22*60+55&&state.time<=23*60+7){addK('ARGUMENT');knowTimeline('argument');return result(true,'你把耳朵贴近门板。里面有人压低声音争执。你听见一句：“把备份交出来。”',2)}return result(true,'门锁没有被撬过。猫眼里也没有光。',1)}if(target==='EVIDENCE'||target==='CEILING'){if(L!=='ROOM_704')return result(false,'你现在接触不到那份证据。',0);if(!hasK('EVIDENCE_LOCATION'))return result(false,'你搜了几处抽屉，但没找到真正重要的东西。也许你还不知道该找哪里。',3);state.loopState.evidence=true;addK('FENG');addK('FENG_MOTIVE');return result(true,'你推开卫生间吊顶检修口。最里面粘着一只小塑料袋——存储卡、偷拍视频目录、备份清单和几张维修工单都在。纸张边缘被捏得发皱，看得出周妍藏它们时非常慌。维修签字反复出现同一个名字：冯川。',3)}if(target==='PHONE')return result(true,`手机电量还剩${state.loopState.phoneBattery}%。陌生号码的对话框静静躺在消息列表里。每次循环开始，它都像提前替你等着那条23:16的求救。`,1);if(target==='DOOR_703')return result(true,'703门锁完好。门链也没有损坏。至少今晚的问题不像是有人强行闯进来。',1);if(L==='KITCHEN'){sfx('fridge');return result(true,'冰箱里还是昨天的外卖。每次循环开始，它都会回到完全相同的位置。',1)}if(L==='BATHROOM')return result(true,'地垫有一点潮。镜子边缘凝着薄薄的水汽，毛巾和洗漱用品都摆得规整，像有人刚刚结束一场再普通不过的晚间洗漱。',1);if(L==='ROOFTOP'){addK('TRUE_CAUSE');return result(true,'护栏边有一道新鲜擦痕，地面还有被鞋底拖过的细印。你终于明白：循环真正锁住的不是“你要不要离开小区”，而是这里会发生的死亡。',2)}if(target==='SCENE'&&L==='ROOM_704')return result(true,'书桌上的便签、收纳架上的杂物和窗边留下的杯子，让704更像一个加班晚归者的独居小屋，而不是抽象的案发现场。',1);if(target==='SCENE'&&L==='CORRIDOR_7F')return result(true,'这条走廊把703、704、705、电梯口和楼梯口串成一条清楚的动线。只要站位对，很多细节其实无处可藏。',1);if(target==='SCENE'&&L==='LOBBY')return result(true,'公告栏、信箱、电梯和通往值班室的过道都在同一空间里。谁来、谁停留、谁上楼，都会留下被人看见的机会。',1);if(target==='SCENE'&&L==='PROPERTY_OFFICE')return result(true,'值班桌上的登记本翻在最新一页，监控画面同时照着楼道与出入口。这里记录的不是戏剧冲突，而是最琐碎也最可信的日常证据。',1);if(target==='SCENE'&&L==='STAIRCASE')return result(true,'楼梯间的转角很多，既适合藏身，也方便人悄悄错开目光。对跟踪与伏击来说，它几乎是整栋楼最关键的夹层空间。',1);return result(true,'你仔细看了一遍，没有发现足以改变判断的新东西。',1)}
function talk(target,content=''){if(target==='ZHOU_YAN'){if(state.location!=='ROOM_704'&&state.location!=='CORRIDOR_7F')return result(false,'周妍不在你面前。你可以给她发消息。',0);if(state.time>=23*60+8)return result(false,'她已经离开704。',0);addK('ZHOU');if(hasK('HELP')||/23[:：]?16|报警|求救/.test(content))grantZhouTrust('HELP',1);if(hasK('CAMERA')||/摄像|偷拍|烟感/.test(content))grantZhouTrust('CAMERA',2);if(state.loopState.zhouTrust>=2){addK('EVIDENCE_LOCATION');return result(true,'你说出了她还没告诉任何人的细节。周妍先是怔住，随后压低声音：“你到底怎么知道这些……算了，证据在卫生间吊顶，最里面那格。23点以后别让我跟那个维修的人单独走。”她明明很怕，却还是在努力把重点说清。',3)}if(state.loopState.zhouTrust===1)return result(true,'周妍握着手机，明显在强撑镇定。她看了你几秒，终于没再把话题岔开：“703？你是不是听到什么了……如果你真想帮忙，先别惊动物业。”',2);return result(true,'周妍眼下发青，像已经紧张了很久。她勉强笑了一下：“我没事，就是704这边一点小麻烦。你怎么突然来问我？”',2)}if(target==='MAINTENANCE_WORKER'){if(hasK('FENG'))return talk('FENG_CHUAN',content);const here=(state.location==='CORRIDOR_7F'&&state.time>=22*60+51&&state.time<=22*60+54)||(state.location==='ROOM_704'&&state.time>=22*60+52&&state.time<23*60+8)||(state.location==='STAIRCASE'&&state.time>=22*60+49&&state.time<=22*60+55);if(!here)return result(false,'那个维修员现在不在你能直接交谈的位置。',0);addK('REPAIRMAN');state.loopState.fengSuspicion+=8;return result(true,'维修员停下动作，先看了眼你身后的703门牌才说：“704报修，我来处理线路。”他的口气不算凶，却刻意把对话截得很短，也没有主动报姓名。',2)}if(target==='FENG_CHUAN'){if(!hasK('FENG'))return result(false,'你还不知道冯川是谁。',0);if(state.time>=22*60+51&&state.time<23*60+8&&['CORRIDOR_7F','ROOM_704','STAIRCASE'].includes(state.location)){state.loopState.fengSuspicion+=10;if(state.loopState.evidence||hasK('CAMERA'))return result(true,'冯川的视线在你脸上停得过久，像在判断你到底知道多少。“住703就回703去，”他说得很平，却比发火更像威胁，“704的事，物业会处理。”',2);return result(true,'冯川盯了你一眼，嘴角甚至带点职业性的敷衍笑意：“704报修，我来处理线路。你住703吧？早点回去，别在走廊逗留。”',2)}return result(false,'冯川现在不在你能直接交谈的位置。',0)}if(target==='GUARD_ZHAO'){if(state.location!=='LOBBY'&&state.location!=='PROPERTY_OFFICE')return result(false,'门卫老赵不在这里。',0);addK('FENG');knowTimeline('feng_arrival');return result(true,'老赵翻开登记本，语气很实在：“小冯，外包维修，今晚22:47刷门禁，说是704报修。这个人平时话不多，来得倒挺勤。”他显然已经把冯川当成熟面孔记住了。',2)}return result(false,'你现在找不到合适的人谈这件事。',0)}
function call(target,content='',method=''){if(target==='POLICE'){state.loopState.policeCalled=true;if(state.loopState.evidence||state.loopState.confession){state.loopState.policeETA=state.time+8;return result(true,'你把具体房号、偷拍视频证据和维修人员信息都报了出去。接警员复述得很仔细，附近巡逻车已经往这边赶。',3)}addK('POLICE_NEED_PROOF');state.loopState.policeETA=state.time+15;state.loopState.fengSuspicion+=25;return result(true,'你能说明风险，却拿不出明确证据。警方仍做了记录，但接警员提醒会先核实情况，物业很可能比警车更早收到电话。',3)}if(target==='DU_COLLEAGUE')return result(true,'小杜：“把每一轮发生的时间记下来，别凭感觉。”',2);if(target==='PROPERTY_OFFICE'){const falseReport=method==='FALSE_REPAIR_REPORT'||(/704/.test(content)&&/漏水|水管|渗水|停电|线路故障/.test(content)&&/骗|假装|谎称|借口|报修|叫|派|让/.test(content));if(falseReport){state.loopState.falseRepairReported=true;return result(true,'你装作什么都不知道，只说704疑似漏水，请物业派人确认。值班员没有多问，只说明会联系今晚值班的外包维修，语气熟练得像这种流程经常发生。',2)}addK('REPAIRMAN');addK('FENG');knowTimeline('feng_arrival');return result(true,'物业查到线路检修记录：“外包维修员冯川，22:47刷门禁。”值班端同时能看到他的工单备注：704，线路检查。',2)}return result(false,'这个电话现在没有意义。',0)}
function message(target,content=''){if(target==='ZHOU_YAN'){addK('ZHOU');if(/23[:：]?16|报警|求救/.test(content)||hasK('HELP'))state.loopState.zhouTrust++;if(/摄像|偷拍|烟感/.test(content)||hasK('CAMERA'))state.loopState.zhouTrust+=2;if(state.loopState.zhouTrust>=2){addK('EVIDENCE_LOCATION');state.loopState.warnedZhou=true;return result(true,'周妍过了一会才回复，像是在反复确认要不要信你：\n“如果你真的知道偷拍的事，证据在卫生间吊顶。23点后别让我跟他单独走。求你。”',2)}if(state.loopState.zhouTrust===1)return result(true,'对方很快回过来：\n“你是703？你怎么会知道我要报警？”\n文字里没有彻底信任，但已经明显慌了。',1);return result(true,'对方过了一会只回了一个问号：“你是703？”',1)}return result(false,'消息没有发给任何有效联系人。',0)}
function hide(target){if(target==='STAIRCASE'){state.location='STAIRCASE';return result(true,arrivalText('STAIRCASE'),2)}if(target==='CORRIDOR_7F'){state.location='CORRIDOR_7F';return result(true,'你关掉手机屏幕，躲在走廊转角等着。',2)}return result(true,'你找了个不显眼的位置等着，但这里看不到关键路线。',2)}
function follow(target){const anon=target==='MAINTENANCE_WORKER';if(target!=='FENG_CHUAN'&&!anon)return result(false,'你现在没有明确的跟踪目标。',0);if(target==='FENG_CHUAN'&&!hasK('FENG'))return result(false,'你还没确认这个名字对应谁。可以说“跟着那个维修工”。',0);if(state.time>=22*60+49&&state.time<=22*60+55){if(!['LOBBY','CORRIDOR_7F','ELEVATOR','STAIRCASE'].includes(state.location))return result(false,'你现在不在能看到维修员经过的位置。先去一楼、七楼走廊或楼梯间。',0);state.location='STAIRCASE';addK('REPAIRMAN');addK('MASTER_KEY');return result(true,'你隔着一层楼跟着维修员上七楼，看见他腰间挂着一串物业维修钥匙。钥匙相互碰撞时，他下意识按住了其中那把贴着704标签的。',3)}if(state.time>=23*60+8&&state.time<=23*60+12){if(!['CORRIDOR_7F','ROOM_704','STAIRCASE'].includes(state.location))return result(false,'你离704的动线太远，现在追不上他们。',0);state.location='ROOFTOP';addK('ROOFTOP');return result(true,'你保持距离跟着冯川和周妍，一路上了天台。周妍走得很快，像是不愿在楼梯间停哪怕一秒。',3)}return result(false,'这个时间点你没有跟上他。',1)}
function test(target,content=''){const anon=target==='MAINTENANCE_WORKER';if(target!=='FENG_CHUAN'&&!anon)return result(false,'你想试探谁？',0);if(target==='FENG_CHUAN'&&!hasK('FENG'))return result(false,'你还没确认“冯川”是谁。可以试探“那个维修工”。',0);const here=(state.location==='CORRIDOR_7F'&&state.time>=22*60+51&&state.time<=22*60+54)||(state.location==='ROOM_704'&&state.time>=22*60+52&&state.time<23*60+8)||(state.location==='STAIRCASE'&&((state.time>=22*60+49&&state.time<=22*60+52)||(state.time>=23*60+8&&state.time<=23*60+12)));if(!here)return result(false,'你现在不在能当面试探维修员的位置。',0);if(/证据|存储卡|摄像|偷拍|警察|录像/.test(content)&&(hasK('CAMERA')||state.loopState.evidence)){addK('CONFESSION_ROUTE');state.loopState.recording=true;state.loopState.confession=true;state.loopState.fengSuspicion=100;return result(true,'你故意说警方已经拿到704里的偷拍视频。冯川先是否认，下一秒却急得脱口而出：“她明明把卡藏在吊顶——”你口袋里的手机正在录音。',3)}state.loopState.fengSuspicion+=20;return result(true,'你放出一个模糊假消息。冯川没有上钩，只是眼神更冷，明显开始提防你。',2)}
function waitAction(method,content=''){let n=2;const m=String(method||content).match(/(\d{1,2})\s*分/);if(m)n=Math.min(10,Math.max(1,+m[1]));const tm=String(method||content).match(/(22|23)[:：](\d{2})/);if(tm){const target=+tm[1]*60+(+tm[2]);if(target>state.time)n=Math.min(15,target-state.time)}return result(true,`你没有做别的事，只是在这里等了${n}分钟。`,n)}
function use(target,method=''){if(target==='KEY'||/钥匙/.test(method)){if(!state.loopState.hasMaintenanceKey&&!hasK('MASTER_KEY'))return result(false,'你手里没有能打开704的钥匙。',0);state.loopState.hasMaintenanceKey=true;sfx('door');return result(true,'你用物业维修钥匙打开了704。',1)}if(target==='CAMERA'||target==='PHONE'){state.loopState.recording=true;return result(true,'你打开手机录音/录像，锁屏后放进口袋。',1)}return result(false,'这个东西现在用不上。',0)}
function place(target,content=''){if(/堵|顶住|卡住|门/.test(content)&&['STAIRCASE','ROOFTOP','CORRIDOR_7F'].includes(state.location)){state.loopState.rooftopBlocked=true;return result(true,'你用身边能找到的东西让消防门无法轻易通过。这个办法只能改变路线，不能代替证据。',2)}return result(true,'你布置了一点东西，但暂时看不出它会改变关键事件。',1)}
function infer(content=''){if(/周妍|23[:：]?17|死亡|坠/.test(content)){addK('TRUE_CAUSE');return result(true,'这个推理和时间线吻合：真正锁住循环的，很可能是23:17发生在周妍身上的事。',1)}if(/冯川|维修|摄像|偷拍/.test(content)&&hasK('CAMERA')){addK('FENG_MOTIVE');return result(true,'你把事实连在一起：维修权限让这个人能合理接近被改装的设备。',1)}return result(true,'你把猜想记下来，但现在还缺少能验证它的事实。',1)}
function resolveAction(a){a=validateAction(a);const action=a.action,target=a.target,method=a.method||'',content=a.content||'';switch(action){case'MOVE':return moveTo(target);case'INSPECT':return inspect(target);case'TALK':return talk(target,content);case'CALL':return call(target,content,method);case'MESSAGE':return message(target,content);case'HIDE':return hide(target);case'FOLLOW':return follow(target);case'WAIT':return waitAction(method,content);case'TEST':return test(target,content);case'USE':return use(target,method);case'PLACE':return place(target,content);case'INFER':return infer(content);default:return result(false,'这个做法在当前环境里没有可执行对象。换一种更具体的说法试试。',0)}}
function normalizeText(s){return String(s||'').trim().replace(/[，。！？、；;]/g,' ').replace(/\s+/g,' ')}
function localParse(raw){const t=normalizeText(raw);if(!t)return null;const placeMap=[[/704|隔壁房间|周妍家/,'ROOM_704'],[/703|我家|家里|回家|玄关/,'FOYER'],[/705/,'CORRIDOR_7F'],[/天台|楼顶|屋顶/,'ROOFTOP'],[/楼梯间|楼梯|消防通道|消防门/,'STAIRCASE'],[/电梯口|电梯/,'ELEVATOR'],[/物业办公室|物业值班室|物业/,'PROPERTY_OFFICE'],[/一楼|大厅|门卫室|门岗/,'LOBBY'],[/便利店|小卖部|商店/,'CONVENIENCE_STORE'],[/走廊|门外|七楼/,'CORRIDOR_7F'],[/客厅/,'LIVING'],[/卧室|房间|床边/,'BEDROOM'],[/厨房|冰箱/,'KITCHEN'],[/卫生间|洗手间|厕所|浴室/,'BATHROOM']];const personMap=[[/周妍|704住户|隔壁女生|隔壁女孩|邻居女生/,'ZHOU_YAN'],[/冯川|小冯/,'FENG_CHUAN'],[/老赵|门卫|保安|门岗/,'GUARD_ZHAO'],[/小杜|同事/,'DU_COLLEAGUE'],[/警察|110|警方/,'POLICE']];const from=(m)=>{for(const[x,v]of m)if(x.test(t))return v;return''};const mentionsMaintenance=/维修工|维修员|维修人员|物业维修|维修的人|修理工|师傅|物业的人/.test(t);const person=()=>from(personMap)||(mentionsMaintenance?(hasK('FENG')?'FENG_CHUAN':'MAINTENANCE_WORKER'):'');
  if(/物业|值班室|报修/.test(t)&&/漏水|渗水|水管|停电|线路|跳闸/.test(t)&&/骗|假装|谎称|借口|说|告诉|叫|派|让|联系|报修/.test(t))return{action:'CALL',target:'PROPERTY_OFFICE',method:'FALSE_REPAIR_REPORT',content:t,confidence:.99};
  if(/报警(?!器)|打110|拨110|叫警察|联系警方/.test(t)&&!/发消息|发微信|发短信|微信|短信|告诉/.test(t))return{action:'CALL',target:'POLICE',method:'PHONE',content:t,confidence:.99};
  if(/录音|录像/.test(t)&&/诈|骗|套话|试探|故意说/.test(t)){const p=mentionsMaintenance?(hasK('FENG')?'FENG_CHUAN':'MAINTENANCE_WORKER'):person();if(p)return{action:'TEST',target:p,method:'RECORD_AND_BLUFF',content:t,confidence:.98}}
  if(/发消息|发微信|发短信|微信|短信|告诉/.test(t)){const p=person();if(p&&p!=='POLICE')return{action:'MESSAGE',target:p,method:'TEXT',content:t,confidence:.96}}
  if(/敲.*704|704.*敲|敲门/.test(t)&&(/704|周妍|隔壁/.test(t)))return{action:'TALK',target:'ZHOU_YAN',method:'KNOCK',content:t,confidence:.96};
  if(/问|聊|交谈|叫住|跟.*说/.test(t)){let p=person();if(!p&&/704/.test(t))p='ZHOU_YAN';if(p&&p!=='POLICE')return{action:'TALK',target:p,method:'ASK',content:t,confidence:.93}}
  if(/跟踪|跟着|尾随|盯着.*走/.test(t)){const p=person();if(p)return{action:'FOLLOW',target:p,method:'FOLLOW',content:t,confidence:.96}}
  if(/骗|诈|假装|试探|套话|故意说|诈一下/.test(t)){const p=person();if(p)return{action:'TEST',target:p,method:'BLUFF',content:t,confidence:.92}}
  if(/躲|藏|埋伏|蹲守|守在|等在/.test(t)){let pl=from(placeMap)||state.location;if(/楼梯/.test(t))pl='STAIRCASE';else if(/704.*门|门口/.test(t))pl='CORRIDOR_7F';return{action:'HIDE',target:pl,method:t,content:t,confidence:.94}}
  const explicitMove=t.match(/(?:^|先|提前|然后|我想)?(?:去|前往|回到|回|进入|到|下楼去|上楼去|过去|走到)\s*(704|703|705|天台|楼顶|屋顶|楼梯|消防楼梯|电梯|物业|值班室|一楼|大厅|门卫|便利店|小卖部|商店|走廊|门外|客厅|卧室|厨房|卫生间|厕所|浴室)/);if(explicitMove){const pl=from(placeMap);if(pl)return{action:'MOVE',target:pl,method:'WALK',content:t,confidence:.98}}
  if(/等|待到|等到|等一会|等等/.test(t))return{action:'WAIT',target:state.location,method:t,content:t,confidence:.94};
  if(/打电话|电话给|联系|拨给/.test(t)){const p=person()||(/物业/.test(t)?'PROPERTY_OFFICE':'');if(p)return{action:'CALL',target:p,method:'PHONE',content:t,confidence:.91}}
  if(/我认为|我觉得|推理|猜测|应该是|说明|推断|怀疑/.test(t))return{action:'INFER',target:'',method:'',content:t,confidence:.84};
  if(/录音|录像|拍照|手机录|开启录音|开启录像/.test(t))return{action:'USE',target:'PHONE',method:t,content:t,confidence:.92};
  if(/检查|看看|看一下|观察|搜|翻|拆|打开|查看|听|找|摸|检查一下/.test(t)){if(/烟感|烟雾报警/.test(t))return{action:'INSPECT',target:'SMOKE_DETECTOR',method:t,content:t,confidence:.99};if(/吊顶|存储卡|证据|备份/.test(t))return{action:'INSPECT',target:'EVIDENCE',method:t,content:t,confidence:.97};if(/704.*门|门.*704/.test(t))return{action:'INSPECT',target:'DOOR_704',method:t,content:t,confidence:.94};if(/703.*门|门锁|门链/.test(t))return{action:'INSPECT',target:'DOOR_703',method:t,content:t,confidence:.92};if(/手机|短信|消息/.test(t))return{action:'INSPECT',target:'PHONE',method:t,content:t,confidence:.92};return{action:'INSPECT',target:'SCENE',method:t,content:t,confidence:.6}}
  if(/钥匙|开704/.test(t))return{action:'USE',target:'KEY',method:t,content:t,confidence:.9};if(/放|夹|堵|贴|撒|顶住|卡住/.test(t))return{action:'PLACE',target:from(placeMap)||'SCENE',method:t,content:t,confidence:.72};if(/去|前往|下楼|上楼|回到|进入|出去|离开|过去/.test(t)){const pl=from(placeMap);if(pl)return{action:'MOVE',target:pl,method:'WALK',content:t,confidence:.95}}const pl=from(placeMap);if(pl&&t.length<=12)return{action:'MOVE',target:pl,method:'WALK',content:t,confidence:.75};return null}
function validateAction(a){if(!a||typeof a!=='object')return{action:'UNSUPPORTED',target:'',method:'',content:'',confidence:0};const action=String(a.action||'UNSUPPORTED').toUpperCase();const target=String(a.target||'').toUpperCase();return{action:ACTIONS.has(action)?action:'UNSUPPORTED',target:TARGETS.has(target)?target:'',method:String(a.method||'').slice(0,160),content:String(a.content||'').slice(0,240),confidence:Math.max(0,Math.min(1,Number(a.confidence)||0))}}
async function parseAction(text){const local=localParse(text);if(local&&local.confidence>=.72){els.parser.textContent='本地规则引擎';return validateAction(local)}const cfg=window.GAME_CONFIG||{};if(cfg.aiFallbackEnabled&&cfg.workerEndpoint){els.parser.textContent='正在理解复杂行动…';const ctl=new AbortController(),ms=Math.max(1500,Math.min(8000,Number(cfg.aiTimeoutMs)||4500)),timer=setTimeout(()=>ctl.abort(),ms);try{const visibleContext={time:fmt(state.time),location:state.location,knowledge:state.meta.knowledge.slice(0,20),loop:state.loop};const res=await fetch(cfg.workerEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:String(text).slice(0,240),visibleContext}),signal:ctl.signal});clearTimeout(timer);if(res.ok){const j=await res.json();const parsed=validateAction(j&&j.action);if(parsed.action!=='UNSUPPORTED'){els.parser.textContent='Cloudflare AI 解析';return parsed}}}catch(e){clearTimeout(timer);els.parser.textContent=e&&e.name==='AbortError'?'AI超时，已回退本地':'AI不可用，已回退本地'}finally{clearTimeout(timer)}}else els.parser.textContent='本地规则引擎';if(local){els.parser.textContent=els.parser.textContent.includes('AI')?els.parser.textContent+' · 低置信本地兜底':'本地规则兜底';return validateAction(local)}return{action:'UNSUPPORTED',target:'',method:'',content:text,confidence:0}}
function processMinute(m){if(m===22*60+47)knowTimeline('feng_arrival');if(m===22*60+52&&(state.location==='CORRIDOR_7F'||state.location==='ELEVATOR')){sfx('elevator');addK('REPAIRMAN');knowTimeline('feng_knock');log('电梯“叮”了一声。一个穿维修服的男人提着工具箱走向704。','clue')}if(m===22*60+56&&['CORRIDOR_7F','ROOM_704'].includes(state.location)){addK('ARGUMENT');knowTimeline('argument');log('704里传来压低的争执声。“……把备份交出来。”','clue')}if(m===23*60+3)knowTimeline('backup');if(m===23*60+8){if(state.loopState.warnedZhou){state.loopState.zhouSafe=true;log('23:08到了。周妍听进了你的警告，没有跟维修员去天台。','clue')}else if(['CORRIDOR_7F','STAIRCASE'].includes(state.location)){addK('ROOFTOP');knowTimeline('leave704');log('704门开了。周妍和维修员一前一后往消防楼梯走。','clue')}}if(m===23*60+11)knowTimeline('rooftop_move');if(m===23*60+16){addK('HELP');knowTimeline('help_message');if(!state.loopState.zhouSafe){sfx('phone');log('手机震了一下。陌生号码：\n“703，帮我报警。”','danger')}}}
function advance(n){if(n<=0){updateUI();return}const from=state.time,to=Math.min(state.time+n,LOOP_END);for(let m=from+1;m<=to;m++)processMinute(m);state.time=to;if(state.loopState.policeETA&&state.time>=state.loopState.policeETA&&!state.loopState.fengDetained&&(state.loopState.evidence||state.loopState.confession)){state.loopState.fengDetained=true;log('楼下传来急促脚步。警方已经进入楼内。','clue')}checkEnding();updateUI()}
function checkEnding(){if(state.time<LOOP_END)return;const l=state.loopState;if(l.evidence&&l.policeCalled&&l.fengDetained&&l.warnedZhou&&(l.confession||hasK('CONFESSION_ROUTE'))){const all=state.meta.knowledge.length>=Object.keys(KNOWLEDGE_LABELS).length;if(all&&hasK('TRUE_CAUSE'))showEnding('《你为什么记得？》','23:17。没有撞击声。\n23:18。警方在七楼控制住冯川。\n\n00:03，周妍就坐在你旁边，你的手机却收到一条来自“周妍”的短信：\n“谢谢。”\n\n发送时间：昨天 23:16。\n\n她抬头看你：“怎么了？”','hidden');else showEnding('《证据》','23:17。\n没有撞击声。没有黑屏。\n\n23:18。\n\n这是你第一次看到这个时间。警方控制住冯川，周妍的备份和你的录音补上最后一块证据。','perfect');return}if(l.evidence&&l.policeCalled&&l.warnedZhou){showEnding('《活到明天》','23:17过去了。周妍没有上天台。\n23:18，时间继续向前。\n\n证据保住了，她也活了下来，但冯川在警方到达前离开了小区。','good');return}if(l.zhouSafe){log('23:17。没有人坠楼。你以为成功了。\n下一秒，玄关的灯重新亮起。','danger');doLoopReset(true);return}doLoopReset(false)}
function doLoopReset(falseSave){addK('LOOP',true);addK('HELP',true);knowTimeline('death');const meta=JSON.parse(JSON.stringify(state.meta)),prev=state.loop;state=baseState();state.meta=meta;state.loop=prev+1;state.meta.totalActions=meta.totalActions||0;els.log.innerHTML='';flash('23:17 → 22:47');log('你猛地睁开眼。\n钥匙还插在703门锁上。手机电量36%。时间：22:47。','danger');if(falseSave)log('你改变了结果，却没有改变循环。仅仅“阻止一次事故”还不够。','clue');updateUI();save()}
function flash(t){els.flash.textContent=t;els.flash.classList.remove('hidden');setTimeout(()=>els.flash.classList.add('hidden'),900)}
function showEnding(title,text,kind){$('#endingTitle').textContent=title;$('#endingText').textContent=text;$('#endingStats').textContent=`循环 ${state.loop} 次 · 已知事实 ${state.meta.knowledge.length}/${Object.keys(KNOWLEDGE_LABELS).length} · 行动 ${state.meta.totalActions} 次`;$('#ending').classList.remove('hidden');save()}
async function submit(){const text=els.input.value.trim();if(!text)return;els.input.value='';log(`> ${text}`,'player');els.send.disabled=true;try{const a=await parseAction(text),r=resolveAction(a);log(r.text,r.ok?'normal':'system');state.meta.totalActions++;if(r.cost>0)advance(r.cost);else updateUI()}finally{els.send.disabled=false;els.input.focus()}}
function renderHotspots(){
  els.hotspots.innerHTML='';
  const map={
    FOYER:[[72,14,25,68,'INSPECT','DOOR_703'],[45,27,19,52,'MOVE','LIVING'],[1,12,33,70,'MOVE','KITCHEN']],
    LIVING:[[0,25,18,66,'MOVE','BEDROOM'],[88,19,12,68,'MOVE','FOYER'],[43,55,20,25,'INSPECT','PHONE'],[22,43,31,42,'INSPECT','SCENE']],
    BEDROOM:[[79,20,21,70,'MOVE','LIVING'],[48,12,29,55,'INSPECT','SCENE'],[0,45,58,50,'INSPECT','SCENE']],
    KITCHEN:[[22,18,20,60,'INSPECT','SCENE'],[72,16,26,70,'MOVE','FOYER'],[0,18,22,66,'INSPECT','SCENE']],
    BATHROOM:[[16,28,27,42,'INSPECT','SCENE'],[38,23,28,34,'INSPECT','SCENE'],[49,57,35,38,'INSPECT','SCENE']],
    CORRIDOR_7F:[[48,25,16,48,'INSPECT','DOOR_704'],[79,12,21,76,'MOVE','FOYER'],[0,11,26,78,'MOVE','ELEVATOR'],[28,20,16,55,'MOVE','STAIRCASE']],
    ROOM_704:[[44,0,17,19,'INSPECT','SMOKE_DETECTOR'],[0,12,16,69,'INSPECT','EVIDENCE'],[80,12,20,78,'MOVE','CORRIDOR_7F'],[47,44,23,44,'INSPECT','SCENE']],
    STAIRCASE:[[37,55,31,40,'HIDE','STAIRCASE'],[54,8,43,83,'MOVE','ROOFTOP'],[10,35,28,53,'MOVE','CORRIDOR_7F'],[0,15,100,80,'INSPECT','SCENE']],
    ROOFTOP:[[0,42,100,58,'INSPECT','SCENE'],[0,0,35,58,'MOVE','STAIRCASE']],
    LOBBY:[[50,25,29,60,'TALK','GUARD_ZHAO'],[72,22,27,67,'MOVE','PROPERTY_OFFICE'],[0,10,32,80,'MOVE','ELEVATOR'],[30,20,30,55,'INSPECT','SCENE']],
    PROPERTY_OFFICE:[[32,53,47,43,'TALK','GUARD_ZHAO'],[22,16,36,45,'INSPECT','SCENE']],
    CONVENIENCE_STORE:[]
  }[state.location]||[];
  for(const[x,y,w,h,a,t]of map){
    const b=document.createElement('button');
    b.className='hotspot';
    b.style.cssText=`left:${x}%;top:${y}%;width:${w}%;height:${h}%`;
    b.tabIndex=-1;
    b.onclick=()=>{ensureAudio();const r=resolveAction({action:a,target:t,method:'CLICK',content:''});log(r.text,r.ok?'normal':'system');state.meta.totalActions++;if(r.cost)advance(r.cost);else updateUI()};
    els.hotspots.appendChild(b)
  }
}
function showModal(t,h){$('#modalTitle').textContent=t;$('#modalBody').innerHTML=h;$('#modal').classList.remove('hidden')}
function showTimeline(){showModal('今夜时间线',TIMELINE.map(([m,l,k])=>{const known=state.meta.timelineKnown.includes(k)||(k==='help_message'&&hasK('HELP'));return`<div class="timeline-row ${known?'':'locked'}"><span class="t">${fmt(m)}</span><span>${known?esc(l):'？'}</span></div>`}).join(''))}
function showKnowledge(){const found=state.meta.knowledge.filter(k=>KNOWLEDGE_LABELS[k]);const total=Object.keys(KNOWLEDGE_LABELS).length;const cards=found.map((k,i)=>`<article class="fact-card"><div class="fact-index">${String(i+1).padStart(2,'0')}</div><div class="fact-body"><h3>${esc(k.replace(/_/g,' · '))}</h3><p>${esc(KNOWLEDGE_LABELS[k])}</p></div></article>`).join('');const body=found.length?`<div class="fact-grid">${cards}</div><div class="fact-summary">已发现 <b>${found.length}</b> 条事实，仍有 <b>${total-found.length}</b> 条尚未解锁。</div>`:`<div class="fact-empty"><p>你还没有整理出任何稳定事实。</p><p class="locked">先经历一次循环，或接触704、维修员、门卫之后，事实图谱才会逐步解锁。</p></div>`;showModal(`事实图谱 · ${found.length}/${total}`,body)}
function showPeople(){
  const cards=[];
  cards.push({name:'你',role:'703住户',text:hasK('LOOP')?'你已经亲自确认：23:17之后时间会回到22:47。除此之外，你仍只是一个普通上班族，只能靠每轮亲眼看到、亲耳听到的事实继续判断。':'刚下班回到703。明天8:30还要上班，你现在只想把这个普通夜晚过完。'});
  if(hasK('ZHOU'))cards.push({name:'周妍',role:'704住户',text:hasK('EVIDENCE_LOCATION')?'她已经偷偷留下备份证据，也一直在判断究竟能信谁。她的警惕不是谜题门槛，而是这几天真实压力留下的结果。':'你只确认了她住在704，而且今晚明显处在紧张状态。更多事情还不能下结论。'});
  if(hasK('REPAIRMAN')&&!hasK('FENG'))cards.push({name:'维修员',role:'物业外包人员 · 身份未确认',text:'今晚22:50前后，他会出现在七楼。你还不知道姓名，也不能仅凭制服判断他和704发生了什么。'});
  if(hasK('FENG'))cards.push({name:'冯川',role:'物业外包维修',text:hasK('CAMERA')||hasK('FENG_MOTIVE')?'他熟悉维修流程和这栋楼的设备，这使他能够把异常行为伪装成普通检修。除此之外，责任仍需要证据继续闭合。':'门卫登记确认了他的姓名与维修身份。至于他为什么来704，目前仍需要继续调查。'});
  if(state.location==='LOBBY'||state.location==='PROPERTY_OFFICE'||hasK('FENG'))cards.push({name:'老赵',role:'门卫 / 值班协助',text:'他熟悉住户、门禁和外包人员，是今晚进出记录的重要见证者，但他并不知道你经历过什么。'});
  showModal('人物观察',cards.map(c=>`<div class="hint-step"><b>${esc(c.name)}</b> · ${esc(c.role)}<br>${esc(c.text)}</div>`).join(''))
}
function showMap(){showModal('地点','<p>703 · 704 · 705 · 七楼走廊 · 消防楼梯 · 一楼大厅 · 物业值班室 · 便利店 · 天台</p><p class="locked">自由输入“去704”“去一楼”“去楼梯间”等即可移动。</p>')}
function hintStage(){if(!hasK('LOOP'))return'START';if(!hasK('ZHOU'))return'FIND_ZHOU';if(!hasK('FENG'))return'FIND_FENG';if(!hasK('CAMERA'))return'FIND_CAMERA';if(!hasK('EVIDENCE_LOCATION'))return'FIND_EVIDENCE';if(!hasK('ROOFTOP'))return'FIND_ROUTE';return'ENDGAME'}
function showHint(){const key=hintStage(),arr=HINTS[key],prev=Number(state.meta.hints[key]||0),level=Math.min(3,prev+1);state.meta.hints[key]=level;save();const current=arr.slice(0,level).map((x,i)=>`<div class="hint-step"><b>${i+1}级</b>　${esc(x)}</div>`).join('');const hist=Object.entries(state.meta.hints).filter(([,n])=>n>0).map(([k,n])=>`<details ${k===key?'open':''}><summary>${k===key?'当前阶段':'已完成阶段'} · 已解锁 ${n}/3</summary>${HINTS[k].slice(0,n).map((x,i)=>`<div class="hint-step"><b>${i+1}级</b>　${esc(x)}</div>`).join('')}</details>`).join('');showModal(`三级提示 · ${level}/3`,`${current}<div class="hint-history"><h3>历史提示回看</h3>${hist}</div>`)}
function resetGame(){
  clearSave();
  state=baseState();
  const ending=$('#ending'),modal=$('#modal');
  if(ending)ending.classList.add('hidden');
  if(modal)modal.classList.add('hidden');
  els.log.innerHTML='';
  els.ideas.innerHTML='';
  els.ideas.classList.add('hidden');
  clearTimeout(ambTimer);
  intro();
  updateUI();
  scheduleAmbient();
  save();
}
function showResetConfirm(){
  showModal('重置存档',`<div class="reset-warning"><p><b>确认从头开始？</b></p><p>这会清除当前循环次数、事实图谱、时间线、提示记录和本轮状态，并回到第一次进入游戏的22:47。</p><p class="locked">声音开关不会被重置。</p><div class="reset-actions"><button id="resetCancelBtn" class="ghost">取消</button><button id="resetConfirmBtn" class="ghost danger-ghost">确认重置</button></div></div>`);
  const cancel=$('#resetCancelBtn'),confirm=$('#resetConfirmBtn');
  if(cancel)cancel.onclick=()=>$('#modal').classList.add('hidden');
  if(confirm)confirm.onclick=resetGame
}
function populateIdeas(){let a=['回客厅看看','检查703门锁','去走廊'];if(hasK('LOOP'))a=['提前去704敲门','去一楼等维修工','躲在消防楼梯'];if(hasK('FENG'))a=['跟踪冯川','检查704门','问周妍物业维修的事'];if(hasK('CAMERA'))a=['告诉周妍我知道偷拍设备','报警','找证据'];if(hasK('ROOFTOP'))a=['提前警告周妍','拿到证据后报警','录音并诈维修工'];els.ideas.innerHTML='';a.forEach(x=>{const b=document.createElement('button');b.className='idea';b.textContent=x;b.onclick=()=>{els.input.value=x;els.input.focus()};els.ideas.appendChild(b)});els.ideas.classList.toggle('hidden')}
function intro(){log('22:47。你加班回到出租屋。钥匙刚插进703的门锁。\n明天8:30还要上班。今晚最好早点睡。');log('你可以直接输入想做的事。常见表达优先由本地规则识别，复杂表达才交给Cloudflare AI；AI超时会自动回退，不会卡住游戏。','system')}
$('#sendBtn').onclick=()=>{ensureAudio();submit()};els.input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ensureAudio();submit()}});$('#timelineBtn').onclick=showTimeline;$('#knowledgeBtn').onclick=showKnowledge;$('#peopleBtn').onclick=showPeople;$('#mapBtn').onclick=showMap;$('#hintBtn').onclick=showHint;$('#ideasBtn').onclick=populateIdeas;els.sound.onclick=()=>setSound(!audioEnabled);$('#resetBtn').onclick=showResetConfirm;$('#modalClose').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')};$('#continueBtn').onclick=resetGame;document.addEventListener('click',()=>ensureAudio(),{once:true});
intro();updateUI();scheduleAmbient();
if(location.search.includes('qa=1'))window.__G2317__={getState:()=>JSON.parse(JSON.stringify(state)),setState:s=>{state=sanitizeState(s);updateUI()},parse:localParse,parseAction,resolve:resolveAction,advance,baseState,addK,showEnding,showHint,showPeople,resetGame,hintStage,validateAction,sanitizeState};
})();
